### ISSUE TITLE
ADC DMA sample / documentation

### ISSUE THREAD

**Issue by taunusflieger** [raspberrypi/pico-feedback#1]
It would be nice to have some additional information on how to use ADC with DMA. The current documentation feels a little bit light (not clear how to setup the DMA transfer)

Use case is to build a solution with a high sampling rate for the ADC, utilizing the scenario described under "4.9.3.5. DMA" in the RP2040 Datasheet. 

Thanks Michael

**Comment by Wren6991** [comment]
I had a look at that section and yes it is a bit sparse! Will take a while to get a doc update pushed through, so in the meantime I thought it might be helpful to add some example code. See https://github.com/raspberrypi/pico-examples/pull/15

Note there is some slightly more helpful information in the register listings, but I'll flesh out that section you pointed out.

**Comment by Wren6991** [comment]
![image](https://user-images.githubusercontent.com/1298595/105843826-20058100-5fd0-11eb-8fb9-be23b4b5b95f.png)

This will appear in the next docs release (should be imminent). If it still lacks clarity or detail then please do ask, otherwise please close if you feel the issue is resolved

**Comment by aallan** [comment]
There should be a V1.1 release later today.

**Comment by aallan** [comment]
V1.1 in the wild.
