### ISSUE TITLE
RP2040 Datasheet - Page 179 - Figure 20 - Capacitor Unit

### ISSUE THREAD

**Issue by Muny** [raspberrypi/pico-feedback#10]
Link to datasheet: https://datasheets.raspberrypi.org/rp2040/rp2040_datasheet.pdf

I noticed a slight typo in the voltage regulator application circuit figure. The capacitor connected to the bottom DVDD pin has a unit of "µnF". I believe this should be just "nF".

**Comment by Wren6991** [comment]
@aallan  it should indeed say nF at the bottom of the figure in 2.10.1 -- could you pass this along to the graphics folks please?

**Comment by aallan** [comment]
Diagram fixed and added upstream. It'll appear in the next documentation release.
