### ISSUE TITLE
Problems following getting-started guide

### ISSUE THREAD

**Issue by wimble99** [raspberrypi/pico-feedback#101]
getting-started-with-pico.pdf simply does not work with new clean pi4. without errors why not? this is totally unacceptable I run vscode as instructed and it has errors and wont work. i have autism and it simply has to work or I start getting a panic attack i get... ELF2UF2 will need to be built PIOASM will need to be built why? then when I look for advice im told to add a generator that is not listed. and no drop down menu to add it. this is totally confusing. strangley i expect product to work please fix

**Comment by lurch** [comment]
> getting-started-with-pico.pdf simply does not work with new clean pi4. without errors why not?

I tested those instructions myself on a "fresh" Raspberry Pi OS SD card on a Pi400 myself before release, and they worked fine. I'll try following them again on a fresh install tomorrow in case something has changed in the meantime.

> ELF2UF2 will need to be built PIOASM will need to be built

Those aren't errors, they're just part of the normal output. Could you show us which other errors you get?
