### ISSUE TITLE
How to switch the CPU clock to its maximal value 

### ISSUE THREAD

**Issue by omikron88** [raspberrypi/pico-feedback#104]
Hello,
How to switch the CPU clock to its maximal value 133 MHz ?

**Comment by daveythacher** [comment]
Is the max 125MHz, 133MHz or 150MHz?

**Comment by omikron88** [comment]
The datasheet says 133MHz

**Comment by aallan** [comment]
> Is the max 125MHz, 133MHz or 150MHz?

As noted in the datasheet the maximum clock frequency is 133MHz, the SDK default frequency is 125MHz.

**Comment by daveythacher** [comment]
> > Is the max 125MHz, 133MHz or 150MHz?
> 
> As noted in the datasheet the maximum clock frequency is 133MHz, the SDK default frequency is 125MHz.

The PLL and Cortex speed is 133MHz. (1.2 and 2.18.1) The clk_sys lists a max nominal of 125MHz. (2.15.3.1) Power consumption shows overclocking to 150MHz. (5.4.1)

I am just pointing out a possible source of confusion. I did not know the SDK frequency.

**Comment by WestfW** [comment]
There is `set_sys_clock_khz(rate, required)`
This is apparently considered part of pico_stdlib, but perhaps that should be mentioned in the hardware_clocks section as well?

It would be nice if the SDK's default system clock were mentioned more clearly somewhere.  Currently, the only place I could find this was buried in the Logic Analyzer example.
