### ISSUE TITLE
PDF Files are too low contrast

### ISSUE THREAD

**Issue by dda-complaint** [raspberrypi/pico-feedback#105]
The documentation for the Pico and its processor do not have black text on a white background. They have grey text on a white background. This makes them difficult to read for people without perfect vision. Please correct this, or offer high-contrast alternatives.

**Comment by aallan** [comment]
This is a duplicate of #13. Issue has been fixed in yesterdays documentation release. Updated PDFs are available on the [Getting Started](https://www.raspberrypi.org/documentation/rp2040/getting-started/) pages.
