### ISSUE TITLE
C/C++ SDK Documentation Typo

### ISSUE THREAD

**Issue by Raupinger** [raspberrypi/pico-feedback#11]
Under **2.7.1. Standard Input/Output (stdio) Support** (Page 20)
It says:
> A UART interface specified by a board configuration header. The default for Raspberry Pi Pico is 115200 baud on GPIO0 (TX) and GPIO1 (TX)

Im fairly certain that should be:
> A UART interface specified by a board configuration header. The default for Raspberry Pi Pico is 115200 baud on GPIO0 (TX) and GPIO1 (RX)

**Comment by Wren6991** [comment]
Thanks! Fixed, will appear in next update
