### ISSUE TITLE
Documentation: USB sie_status CONNECTED (bit 16) should be R-WC instead of RO

### ISSUE THREAD

**Issue by hathach** [raspberrypi/pico-feedback#110]
RP2040 Datasheet v1.2 Table 415. USB: SIE_STATUS Register page 413, CONNECTED (bit 16) is both WC and read-only making it R-WC. Read to determine the current state of connection (connected/disconnected), clear to ack the interrupt event.

![image](https://user-images.githubusercontent.com/249515/109635524-121dbf80-7b7d-11eb-9e13-89d4ec646c7a.png)

The hint is at USB INTS register 

![image](https://user-images.githubusercontent.com/249515/109635608-29f54380-7b7d-11eb-8d02-c49198e2cbd6.png)

**Comment by liamfraser** [comment]
Thanks. @lurch is going to look at this.

**Comment by aallan** [comment]
@lurch Did you manage to take a look, or is it still on backlog?

**Comment by lurch** [comment]
Still on backlog.

**Comment by lurch** [comment]
Fixed internally. Will be included when we next publish the databook PDFs.
