### ISSUE TITLE
How do I get  100nanosecond delay

### ISSUE THREAD

**Issue by EngineerWill** [raspberrypi/pico-feedback#123]
I want to get a 100 nanosecond delay, but I can only get a 1us delay through sleep_us() function.

I tried to use a for loop for the delay, but it seems to be optimized by the compiler to skip the for loop.

I don't know if there is any way to delay 100 nanosecond.

Pico system clock is 125 MHz.

**Comment by lurch** [comment]
I've got a vague memory of a similar question cropping up before. Does section 4.6.1.1 in the RP2040 datasheet help?

**Comment by kilograham** [comment]
Well for sleeping <1us as you say there is no library function. You can use the ARM systick counter and a loop if you want to wait arbitrary numbers of cycles, though that seems like overkill if you only want to wait 12 or so.

Alternatively you can use an assembly loop (with arm volatile)... or do something like the 8us sleep tat is in divider.h which just use 4 2 cycle branches.

```
static inline void hw_divider_pause(void) {
    asm volatile (
    "b _1_%=\n"
    "_1_%=:\n"
    "b _2_%=\n"
    "_2_%=:\n"
    "b _3_%=\n"
    "_3_%=:\n"
    "b _4_%=\n"
    "_4_%=:\n"
    :: : );
}
```

You could do something in C too but as you say you need to convince the compiler it does something useful (e.g. read something volatile).

Not sure what you are trying to do with that short a sleep, but if you really care about timing (and not being interrupted) i'd use PIO instead.
