### ISSUE TITLE
Documentation: Bug: Typo in Constant Value

### ISSUE THREAD

**Issue by soundpaint** [raspberrypi/pico-feedback#124]
Table 280 (PHASE Register) in Section 2.17.8 (List of ROSC Registers) of RP2040 datasheet reads:

11:4 | PASSWD | set to 0xaa0, any other value enables the output with shift=0 | RW | 0x00

Obviously, the constant 0xaa0 does not fit into the range of 8 bits (11:4).  Maybe the constant should read 0xaa?  Or 0xa0?

**Comment by lurch** [comment]
~~ping @liamfraser~~

**Comment by lurch** [comment]
I managed to figure this one out myself - it should say `0xaa`.
Fixed internally, will be included in next release of PDFs.
