### ISSUE TITLE
Pico Python SDK Guide - Spelling Error, Omission,  & Tutorial Usability Considerations

### ISSUE THREAD

**Issue by bntmps** [raspberrypi/pico-feedback#126]
Greetings from across the pond!

I found a couple of spelling errors that you might already know about, but I would like you to be aware just in case.

Spelling Error found Chapter 3 / Page 12      
    ubinascii modile - I could not find the word modile in my textbooks :-)

Omission in Chapter 3  / Page 17 - last paragraph     
    missing the word "do" - ...it easy to "" basic... -

**Suggestions for consideration**
I would like you to know that I read the entire Pico Python SDK document, and I did all of the examples/tutorials.  I encountered difficulties in transitioning from the **minicom** tutorial in Chapter 3 to the **Thonny** tutorial in Chapter 4.  My Command Line window was still active with minicom when I tried the **Thonny** portion of the tutorial.  **Thonny** did not work until I closed the Command Line window with **minicom**.

I also experienced issues transitioning from the **Thonny** tutorial to the **rshell** tutorial. I had to quit **Thonny** and restart the Pico for the **rshell** tutorial to work.

You might consider including instructions that will facilitate an easy flow between examples for new "inexperienced" users (like me) who read the Pico Python SDK document from beginning to end.

I am hopeful the contents in this submittal are useful (for newbies).

Be well!

**Comment by lurch** [comment]
I've just fixed the two typos you mentioned, thanks. Unfortunately we're too busy with other stuff to have time to make substantial changes to the rest of the MicroPython documentation.
