### ISSUE TITLE
Documentation: Typo(?) in Output Priority Signal Names

### ISSUE THREAD

**Issue by soundpaint** [raspberrypi/pico-feedback#128]
Sect. 3.5.6.1 "Output Priority" of RP2040 datasheet says:
"This occurs separately for output levels and output **values**"
I guess, this should read instead:
"This occurs separately for output levels and output **directions**"
Otherwise, I wouldn't get its meaning. :-)

By the way, "output direction" itself is somewhat misleading, since changing the direction will turn the output into an input, as far as I understand.  Maybe the term "output direction" is a somewhat (con)fused version of "output enable" vs. "pin direction"?

**Comment by aallan** [comment]
Fixed in the documentation.
