### ISSUE TITLE
Use more legible fonts for datasheet

### ISSUE THREAD

**Issue by WestfW** [raspberrypi/pico-feedback#13]
The font used for most text in the rp2040 datasheet  (Hmm.  And other pico-related documents as well) is very thinly stroked (or something), and difficult to read.
I've attached a screenshot showing the 2040 datasheet next to a similarly scaled output from the RPi 4 datasheet, and a similar screenshot comparing it with a microchip datasheet, both of which are much more legible.
<img width="485" alt="Screen Shot 2021-01-24 at 10 15 08 PM" src="https://user-images.githubusercontent.com/425027/105668505-4e7d4200-5e92-11eb-9da8-c6d331650fca.png">

<img width="360" alt="Screen Shot 2021-01-24 at 9 44 47 PM" src="https://user-images.githubusercontent.com/425027/105668665-a9169e00-5e92-11eb-8e32-b5baaeb88382.png">

(perhaps I am just getting old.)

**Comment by aallan** [comment]
One of the considerations made when choosing the font for the datasheets was printing, the legibility when printed on paper was a significant factor in the choice, as it's possible that the books may be made available in print at some point in the future. 

If you're having problems reading the text on screen, using your PDF viewer's zoom function might be an option?

**Comment by lonetech** [comment]
Unfortunately this is precisely what PDF, DVI etc are designed to be bad at - they were meant to keep exact layout and font choices. Zooming, particularly with as dense a document as this, easily leads to being unable to see the whole column, let alone page. I wound up rotating my monitor 90 degrees to be able to view a whole page large enough to read comfortably. Perhaps you could consider also publishing a more reformatting friendly format, such as ePub, HTML or ODT? 

Getting old is a normal thing, and enabling a broader audience is good, particularly when the difficulty is unrelated to the subject matter and can be provided as an additional option. 

As a workaround, Calibre can convert documents between a variety of formats, and has a rudimentary viewer too. Sadly, it does a poor job with some formatting in the RP2040 datasheet, e.g. losing all the figures and tables. Most rewrapping PDF viewers do similarly. 

Calibre is also good for keeping track of hundreds of reference manuals.

**Comment by aallan** [comment]
The toolchain also generates reflowable ePub, although it's still a little buggy in places, and we're thinking about releasing that. Would that resolve your issues?

**Comment by aallan** [comment]
I'll take the thumbs up as a yes. Okay, good to know. I'll generate an internal Jira for myself to look at this sometime this week. Thanks for the feedback!

**Comment by lonetech** [comment]
Possibly a bit quick to close, as I'm not the submitter, nor have either of us had a chance to try the ePub version. But I think it's worth a try.

**Comment by aallan** [comment]
Oops! Sorry, I'm triaging a bunch of feedback, didn't spot you weren't the OP. Reopened! 😄

**Comment by descartes** [comment]
Printed the shorter docs on my colour laser (Xerox VersaLink C400) - looks good but font rather slender for a 600dpi entry level printer. Printed the C SDK docs on my black & white laser (Brother HL-5250DN) - font is somewhat pixelated and the typeface where it is in colour is even worse. Having the grey box behind is wasted toner - it doesn't help readability.

For visual access reasons alone for those with old eye balls or ones that aren't working as well, a 'fatter' font would be appropriate.

**Comment by lurch** [comment]
WRT "reflow tools", note that the PDFs' licence doesn't allow redistribution of modified versions.

**Comment by WestfW** [comment]
I'm comparing the RP2040 datasheet to many other data sheets that I've read, from many vendors, and it has the worst legibility.

Zooming in obviously helps, but it seems to help less than I expect.

Is it also possible that the font **color** is set to something other than "black"?  I thought I had zoomed in enough to eliminate that as a possibility, but perhaps not.  Here's a "way zoomed in" (~1inch line spacing on my 4k 29inch monitor) comparison with a Microchip datasheet...

<img width="858" alt="Screen Shot 2021-01-25 at 2 35 42 PM" src="https://user-images.githubusercontent.com/425027/105774866-b1b2b700-5f1a-11eb-9c99-c286e7d23559.png">

**Comment by lurch** [comment]
Maybe we should use Comic Sans :rofl:

**Comment by lonetech** [comment]
> Is it also possible that the font **color** is set to something other than "black"? 

Yes. It is 80% dark gray. Figures seem to use 89% dark gray. This could be the core issue (though the font is also spindly and small).

**Comment by lonetech** [comment]
Incidentally, I found that the reader I prefer on my Kobo eink tablet, koreader, supports not only reflow but even contrast adjustment and cropping, both of which help read this document. Koreader is available for many platforms but its UI may be awkward, as it's designed for e-readers. http://koreader.rocks/

**Comment by rowpie** [comment]
I agree that the (PDF) documents are too difficult to read.  On screen and when printed.  It does appear that the font strokes are too thin.  I suggest a change of font is required.

**Comment by WestfW** [comment]
> One of the considerations made when choosing the font for the datasheets was printing, the legibility when printed on paper was a significant factor in the choice

Assuming that the fonts/colors used are the same in the "getting started with micropython ..." book that HAS been printed, there are similar complaints there:

https://www.eevblog.com/forum/microcontrollers/raspberry-pi-pico/msg3444954/#msg3444954

> The book is written for an absolute beginner with exceptional eyesight.  Damn the font is small!  These people have no respect for old people!

**Comment by swetland** [comment]
I have to agree -- as someone who spends a lot of time looking through TRMs, UMs, and Datasheets in PDF, the RP2040 stands out as unusually high quality content and the absolute worst readability of any I've dealt with (even full screen on a 30" display). Please consider 100% black for text (reducing contrast hurts) and a heavier font.  The thin vertical stems really do impact readability.

**Comment by aallan** [comment]
Due to the way the PDFs are generated there are some formatting issues that we're keeping track of internally. We're also going to explore some options around fonts. I'm hoping to release some reflowable ePub versions of the documentation either this week or next, which might be useful for folks. We're absolutely going to look at this, but right now we're still very close of launch and there is a lot of feedback around content to get through. Due to toolchain issues just switching out the font isn't necessarily a simple matter.

**Comment by HeadBoffin** [comment]
> Due to toolchain issues just switching out the font isn't necessarily a simple matter.

Huh - what witch craft is this?

As suggested on the forum, change control like Word would be useful - or strike throughs - so we can see what's changed - with searchable text like "Here be changes". Only until things settle down.

**Comment by aallan** [comment]
After some internal discussion we're going to be updating the fonts as you can see below when the next PDF documentation release happens, probably at the end of next week.

<img width="1627" alt="Screenshot 2021-02-10 at 16 54 28" src="https://user-images.githubusercontent.com/53625/107562278-7fba7980-6bd7-11eb-98a2-edae9445fdbc.png">

**Comment by aallan** [comment]
Updated PDFs are now available on the [Getting Started](https://www.raspberrypi.org/documentation/rp2040/getting-started/) pages.

**Comment by swetland** [comment]
Thanks!  The new docs are significantly more readable.
