### ISSUE TITLE
Unable to set UART TXE and RXE bits

### ISSUE THREAD

**Issue by alexandruradovici** [raspberrypi/pico-feedback#135]
While porting Tock (written in Rust, I am not able to use the SDK libraries) to RP2040, I am trying to enable the UART transmitter. I think I have followed all the steps,. but setting the UARTCR TXE and RXE bits seems to have no effect. 

Setting UARTEN works, but writing 1 to TXE and RXE keeps the bits low. Does anyone have any idea why this might happen?

I did set the baudrate to 115200 (the computed value is 115207).

**Comment by alexandruradovici** [comment]
I found the issue, I did not notice a gap between UARTFR and UARTILPR and I was not written to the correct register.

On the other hand, it was not clear that UARTEN and TXE have to be set at the same time.

**Comment by fivdi** [comment]
> On the other hand, it was not clear that UARTEN and TXE have to be set at the same time.

I don't believe this to be true. My comments related to UARTEN and TXE are so bad that I just deleted them to avoid further confusion.
