### ISSUE TITLE
Documentation: RP2040 Datasheet - Section 4.3.15.4. Operation of Interrupt Registers

### ISSUE THREAD

**Issue by fivdi** [raspberrypi/pico-feedback#137]
In release 1.4 of the RP2040 Datasheet, section 4.3.15.4. "Operation of Interrupt Registers" is a subsection of section 4.3.15. "DMA Controller Interface".

This is strange as the "Operation of Interrupt Registers" doesn't have a much to do with the "DMA Controller Interface".

Perhaps it would be better if section 4.3.15.4. "Operation of Interrupt Registers" was a subsection of section 4.3 "I2C".

**Comment by lurch** [comment]
Yes, this was a side-effect of the way the documentation in this chapter was copy'n'pasted from the Synopsys documentation.
Will be fixed in the next version of the PDFs, thanks.

**Comment by aallan** [comment]
"Synopsys Proprietary. Used with permission."

<img width="862" alt="Screenshot 2021-04-09 at 21 57 13" src="https://user-images.githubusercontent.com/53625/114239891-92a2bd80-997e-11eb-90f7-52e4a6ae56bc.png">

**Comment by fivdi** [comment]
C'est la vie
