### ISSUE TITLE
Another minor typo in the C/C++ Documentation 

### ISSUE THREAD

**Issue by Raupinger** [raspberrypi/pico-feedback#14]
Under **3.2.1.3. CMake File** (Page 33)
> pico_generate_pio_header(): Declare that we have a PIO program, hello.pio, which we want to be built into a C header for use with out program

should probably be
> pico_generate_pio_header(): Declare that we have a PIO program, hello.pio, which we want to be built into a C header for use with our program

**Comment by Wren6991** [comment]
Thank, fixed upstream, will appear in next release
