### ISSUE TITLE
Resetting a Pico from the command line with OpenOCD

### ISSUE THREAD

**Issue by fivdi** [raspberrypi/pico-feedback#140]
Given that the Pico doesn't have a reset button, consider adding a section to "Getting started with Raspberry Pi Pico" which says that the Pico can be reset from the command line with openocd using the following command:

```
openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "init; reset; exit"
```

A good place for this might be Chapter 5. Flash Programming with SWD

**Comment by lurch** [comment]
Yes, we do already document `openocd -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg -c "program blink/blink.elf
verify reset exit"` so it probably makes sense to add your suggestion also.

**Comment by aallan** [comment]
Fixed in the documentation. Will be present in the next release.
