### ISSUE TITLE
[windows] pico not showing up on any com port

### ISSUE THREAD

**Issue by n-mam** [raspberrypi/pico-feedback#145]
I received my pico today and the blink test worked fine.. However I don't see any COMx device being created. This is how my devmgmt looks. This is on Windows 10 (installed around a month back). I couldn't find any RPI KB which highlights which is the exact USB to serial driver needed for this to work.. 

![image](https://user-images.githubusercontent.com/17683324/115405595-04df9180-a20c-11eb-9611-182448b4a0d5.png)

**Comment by aallan** [comment]
> I received my pico today and the blink test worked fine.. 

Not sure what you mean by "blink test", did you install the `blink.uf2` file on your Pico?

> However I don't see any COMx device being created. 

Not sure why you'd expect one.

For instructions on how to get started with Raspberry Pi Pico on Windows 10 with the C SDK, see [_"Getting started with Raspberry Pi Pico"_](https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf), especially Section 9.2.

For instructions on how to get started with Raspberry Pi Pico with MicroPython, see [_"Raspberry Pi Pico Python SDK"_](https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-python-sdk.pdf) which walks you through installing Thonny.

**Comment by n-mam** [comment]
> Not sure what you mean by "blink test", did you install the blink.uf2 file on your Pico?

yes

> Not sure why you'd expect one.

page 14 of the same guide which you pointed me at we have :

`With your Raspberry Pi Pico connected directly to your Raspberry Pi via USB, see Figure 2, you can see the text by
installing minicom:`  what is that all about then ? Shouldn't one expect an equivalent COM port USB to serial connectivity on Windows ?

**Comment by lurch** [comment]
> Shouldn't one expect an equivalent COM port USB to serial connectivity on Windows ?

Yes, after flashing the `hello_world.uf2`; but your original post implied you were expecting a COM port from the `blink.uf2`?  Can you give more details about exactly what you've done please? (it's always difficult to try and second-guess)

**Comment by aallan** [comment]
> > Not sure why you'd expect one.
> 
> page 14 of the same guide which you pointed me at we have :
> 
> `With your Raspberry Pi Pico connected directly to your Raspberry Pi via USB, see Figure 2, you can see the text by installing minicom:` what is that all about then ? Shouldn't one expect an equivalent COM port USB to serial connectivity on Windows ?

The `blink.uf2` binary just blinks the LED on and off again. There is no UART expected when running the Blink example. The sections (Section 4.3 and 4.4) you mention are talking about the `hello_world.uf2` binary. Scroll down on [this page](https://www.raspberrypi.org/documentation/rp2040/getting-started/#getting-started-with-c) to the "_Say 'Hello World'_" section and download the UF2 file there.

**Comment by n-mam** [comment]
we can leave blink aside for a while. I just highlighted that initially to point out that the board was up and running fine on arrival.. nothing more. My question is what triggers the COM port creation like what has been highlighted on page 12 (i.e. besides directly hooking up to the UART pins directly via a USB to serial convertor) ? is it program specific ?

**Comment by aallan** [comment]
>  is it program specific ?

Yes for programs written using the C SDK. No for MicroPython which presents the REPL over USB CDC Serial.

**Comment by aallan** [comment]
See Chapter 4 of [_"Getting started with Raspberry Pi Pico"_](https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf) for discussion of how to write a program with UART or USB serial enabled.

**Comment by n-mam** [comment]
Indeed it does show up on flashing the hello world sample: Thanks for the pointer

![image](https://user-images.githubusercontent.com/17683324/115418571-36aa2580-a217-11eb-9af6-71cb07726c7e.png)

**Comment by AdityaC4** [comment]
For me, it still does not show up even if I use Hello world example. I changed some settings configuring my other devices using Zadig for Pulseview and while doing that my pico was connected and I think I messed up the drivers. Is there a way to fix this?

it shows as `Board CDC` if I flash the `hello_usb.uf2`, but doesn't show any COM port when I flash `hello_serial.uf2`.
