### ISSUE TITLE
Question: C++ wrapper [around C SDK] in progress?

### ISSUE THREAD

**Issue by Reneg973** [raspberrypi/pico-feedback#149]
Hi there,

is there anybody out there who thinks about (or already began) writing a C++ wrapper around this C functions?

**Comment by lurch** [comment]
FYI the existing SDK _can_ be used with C++ code - see e.g. https://github.com/raspberrypi/pico-sdk/tree/master/tools/elf2uf2

Although as the existing SDK supports both C and C++, it might not as be as "C++ friendly" as a wrapper which _only_ supported C++ and not C ? :man_shrugging:

**Comment by Reneg973** [comment]
> FYI the existing SDK _can_ be used with C++ code - see e.g. https://github.com/raspberrypi/pico-sdk/tree/master/tools/elf2uf2.

Thanks for this extraordinary recentness.

**Comment by kilograham** [comment]
> FYI the existing SDK _can_ be used with C++ code - see e.g. https://github.com/raspberrypi/pico-sdk/tree/master/tools/elf2uf2
> 

Note `elf2uf2` is not strictly an application built using the SDK (though it is written in C++)

> Although as the existing SDK supports both C and C++, it might not as be as "C++ friendly" as a wrapper which _only_ supported C++ and not C ? 🤷‍♂️

Yes all APIs are C, though the headers may be included by C++, and also C++ is a supported language, but there are no official C++ wrappers.

**Comment by Reneg973** [comment]
Yes I know all this. I asked for a developer, who already began implementing such a wrapper or maybe one, who is interested in developing one together

**Comment by fivdi** [comment]
@Reneg973 Maybe someone over at the pico-sdk forum has more information: https://www.raspberrypi.org/forums/viewforum.php?f=145

**Comment by Reneg973** [comment]
@fivdi may be a good idea, thanks
