### ISSUE TITLE
Micropython rshell section would benefit from at least one example

### ISSUE THREAD

**Issue by pelwell** [raspberrypi/pico-feedback#15]
For people not using Thonny, rshell is a necessity for copying the .py file to the RP2040. The current documentation shows how to invoke rshell, but then refers the read to the project documentation, which unfortunately uses /flash rather than /pyboard in most of its examples. A single example of how to install a python program using rshell would be helpful.

**Comment by aallan** [comment]
@nathan-contino Our oldest still open issue (for the [Micropython book](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf)). Please make it go away. 😄

**Comment by aallan** [comment]
Fixed in the documentation. Will be present in the next release.
