### ISSUE TITLE
Cycle count for LDR/STR instructions

### ISSUE THREAD

**Issue by urish** [raspberrypi/pico-feedback#154]
The datasheet specifies 1 or 2 clock cycle, with the following footnote (Table 81 / section 2.4.3.3):

> 2 if to AHB interface or SCS, 1 if to single-cycle I/O port.

However, the word "SCS" doesn't appear anywhere else in the datasheet.

If I understand correctly, ROM, SRAM, and Flash XIP are all connected through the AHB interface, so reading (and also writing, in case of SRAM) takes two clock cycles. SIO takes one cycle (as the name implies).

<strike>How about the APB bus? is it 2 cycles as well?</strike>

Edit: According to section 2.1.3:

- APB bus reads take 3 cycles (2+1)
- ABP bus writes take 4 cycles (2 + 2)

What about the Cortex-M0+ Internal registers/PPB_BASE (e.g. VTOR)?

**Comment by lurch** [comment]
> How about the APB bus?

See section 2.1.3 of the RP2040 datasheet.

(I'm afraid I don't know anything about your other questions)
ping @kilograham @Wren6991 @nickfrancis55

**Comment by urish** [comment]
Thanks @lurch, I updated my original question with the new information

**Comment by aallan** [comment]
> The datasheet specifies 1 or 2 clock cycle, with the following footnote (Table 81 / section 2.4.3.3):
> 
> > 2 if to AHB interface or SCS, 1 if to single-cycle I/O port.
> 
> However, the word "SCS" doesn't appear anywhere else in the datasheet.

As noted at the beginning of Section 2.4, the material has been excerpted from the [Cortex-M0+ Technical Reference Manual](https://developer.arm.com/documentation/ddi0484/latest). I'd therefore look there for further clarification on this one.

**Comment by urish** [comment]
> As noted at the beginning of Section 2.4, the material has been excerpted from the Cortex-M0+ Technical Reference Manual. I'd therefore look there for further clarification on this one.

Very useful advice! SCS stands for System Control Space (address range 0xE000E000 to 0xE000EFFF), so I guess this answers the last part of my question, about Cortex-M0+ Internal registers.

Summarizing my findings so far in a table:

| Base Address | Type                      | Cycles                  |
| ------------ | ------------------------- | ----------------------- |
| 0x00000000   | ROM                       | 2                       |
| 0x10000000   | XIP                       | 2                       |
| 0x20000000   | SRAM                      | 2                       |
| 0x40000000   | ABP Peripherals           | 3 for read, 4 for write |
| 0x50000000   | AHB Peripherals           | 2                       |
| 0xd0000000   | SIO                       | 1                       |
| 0xe0000000   | Cortex-M0+ internal (SCS) | 2                       |

Seems like I have all the information I need for now, so closing this issue.

Thanks for the fast turn-around, and please correct me if anything is incorrect.

**Comment by kilograham** [comment]
Note of course that XIP is 2 cycles at best, it may be longer if it misses the XIP cache.

**Comment by urish** [comment]
> Note of course that XIP is 2 cycles at best, it may be longer if it misses the XIP cache.

Thanks for the clarification! How can the XIP access time be calculated? 

Is section 4.10.10.6 the right place to look for the answer?

Looking at the [second stage boot](https://github.com/raspberrypi/pico-sdk/blob/afc10f3599c27147a6f34781b7102d86f58aa5f6/src/rp2_common/boot_stage2/boot2_w25q080.S#L39), it seems like the SPI frequency is just 1/4th of the clock frequency. 

Though, in a different place in the datasheet, it says: "The maximum frequency of the bit-rate clock (sclk_out) is one-half the frequency of ssi_clk"

If I understand correctly, for every cached XIP read, we need to send the address (24 bit / 6 SCLK cycles in quad mode), then read the data (16 bit for a thumb instruction / 4 SCLK  cycles), which means we need at least 10 SCLK cycles / 20 (or 40?) system clock cycles. Or this I get this wrong?
