### ISSUE TITLE
Recommended terminal software for Mac is expensive 

### ISSUE THREAD

**Issue by ddwwcc** [raspberrypi/pico-feedback#16]
In the documentation for Pico, the recommended terminal software for a Mac is Serial. I hear that this package is very good, but it's also expensive. Cheaper or free open source alternatives should be noted.

**Comment by ghollingworth** [comment]
I always used to just use screen, I think it's available as standard...

**Comment by aallan** [comment]
Thanks, and as I mentioned in the Pico Discord there are alternatives; screen, minicom, CoolTerm (if you want graphical). I'll update the documentation with some alternatives. Meant to do this pre-launch and didn't get there!

**Comment by aallan** [comment]
Fixed upstream. Will be in next docs release.
