### ISSUE TITLE
Exiting second stage flash

### ISSUE THREAD

**Issue by tweiss-tgm** [raspberrypi/pico-feedback#166]
Hello!

I was trying to work with the rp2040 without the sdk, and after some troubleshooting I got a working second stage flash (working as in I could control GPIOs and similar). Now the problem I am facing is that I am not quite able to exit the second stage flash and execute code from SRAM. I know that there's XIP, but I wanted to shadow my code into SRAM and branch to it. 

As it seems I am not able to branch to the code, or my "copying" is just wrong.

Following is my second stage flash code and the output of "readelf" to show, that at least the address where I am copying from is correct:

```
.cpu cortex-m0plus
.thumb

.section .boot2
      // source addr
      ldr r4, =(0x10000100)
      // dest addr
      ldr r5, =(0x20000000)
      // num. of bytes to copy
      ldr r6, =(0x400)
      // counter
      mov r7, #0x00

transfer:
      cmp r7, r6
      beq finish

      // load word of code
      mov r2, r4
      add r2, r7
      ldr r0, [r2]

      // store word into sram
      mov r2, r5
      add r2, r7
      str r0, [r2]

      add r7, #0x04
      b transfer

finish:
      // branch to sram
      add r5, #0x01
      blx r5

.end
```

And the output of "readelf" (I removed "unnecessary" sections from the output)

```
> readelf -S main.elf
There are 12 section headers, starting at offset 0x10708:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .boot2            PROGBITS        10000000 010000 000100 00  AX  0   0  1
  [ 2] .text             PROGBITS        10000100 010100 00011c 00  AX  0   0  4
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  y (purecode), p (processor specific)
```
(Little note, I looked into the elf file of the "blink" example of the sdk, and the "text" section is 8-byte aligned, which confuses me a bit. I tried to change the alignment from 4 to 8, but it had no effect)

As it seems to me, the SRAM address should be viable for code execution, furthermore I am accessing the address word aligned, so this shouldn't be a problem too. The amount of bytes I am copying are quite randomly set, but high enough to include all of the code, and as I think, it shouldn't matter too much, if I copy some garbage from flash to SRAM.

I would appreciate any kind of help, ideas, directions, as of why my code seems to never reach the code in SRAM. Thanks in advance!

**Comment by kilograham** [comment]
You cannot read from flash (via CPU instruction) to copy it to RAM without first enabling XIP (which is the purpose of the second stage which you've removed/replaced).

I suggest you try forums (https://www.raspberrypi.org/forums/viewforum.php?f=143) for help
