### ISSUE TITLE
pico not run pio program after load uf2 and power on again.

### ISSUE THREAD

**Issue by simonzty** [raspberrypi/pico-feedback#169]
My project use a HCSR04 module and pico PIO to measure distance, I generate uf2 file by VSCode properly, and pico is running ok when it just loaded uf2 file . When I power pico off, and power on again, it can't output PIO pulse to trigger HCSR04. I don't know what happen with pico. Hope someone can help me, thx!
If load uf2 again, it can work, but still not run if power switched. OLED which run in the same program is alway OK. I test pio_blink from official example folder, it's ok.

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/viewforum.php?f=143), so I’m closing this issue. But please follow up with further comments if you have specific feedback around the documentation or example code provided with Pico.
