### ISSUE TITLE
Typo in datasheet? (USB)

### ISSUE THREAD

**Issue by urish** [raspberrypi/pico-feedback#172]
The table describing the SIE_STATUS (table 414/page 422) calls the LSB "VBUS_DETECTED":

![image](https://user-images.githubusercontent.com/892318/124445848-9466fc00-dd88-11eb-939c-c82f08fdf65b.png)

However, further references to the same bit call it VBUS_DETECT (e.g. bit 11 in INTR/INTE/INTF/INTS registers, pages 431-434):

![image](https://user-images.githubusercontent.com/892318/124445908-a2b51800-dd88-11eb-8eab-ab0551cce4ac.png)

Datasheet version:
build-date: 2021-06-23
build-version: ced2189-clean

**Comment by aallan** [comment]
Ping @liamfraser

**Comment by liamfraser** [comment]
Rather than change either of the register names (affecting software) the simplest thing is to update the reference of the VBUS_DETECT interrupt to say SIE_STATUS.VBUS_DETECTED instead of the incorrect SIE_STATUS.VBUS_DETECT

**Comment by aallan** [comment]
> Rather than change either of the register names (affecting software) the simplest thing is to update the reference of the VBUS_DETECT interrupt to say SIE_STATUS.VBUS_DETECTED instead of the incorrect SIE_STATUS.VBUS_DETECT

Is this a TSV thing, or is it a manual Asciidoc fix?

**Comment by lurch** [comment]
It's a TSV thing. If @liamfraser is too busy to fix it himself, feel free to assign it to me and I'll add it to my backlog.

**Comment by liamfraser** [comment]
I'll sort it now

**Comment by liamfraser** [comment]
Closing this issue as it will go into the next datasheet / sdk release
