### ISSUE TITLE
Cross-reference to errata in main body of datasheet

### ISSUE THREAD

**Issue by dhalbert** [raspberrypi/pico-feedback#173]
Traditionally, hardware data sheets have not referenced errata in the main body of the datasheet. Instead, a hardware datasheet describes the idealized version of a product, and a separate errata document describes deviations from the ideal.

The RP2040 datasheet is better already because it includes the specs and errata are in the same document. I propose that the main body of the datasheet also include cross-references and/or warnings that an erratum exists for a described feature. For example, I was intrigued by the XOSC `COUNT` register when I first read about it, and thought about how to use it, but only weeks later found out from the errata it unfortunately is not reliable.

The RP2040 datasheet is already a model of clarity in the world of datasheets. In the long run, I hope that the RPi datasheets would set an example that would encourage all manufacturers to make their datasheets more useful an accessible.

It is true that software specs also do not typically include cross-references to bug reports or issues. When something doesn't work, one must search the relevant issue lists. That is not the best situation either.

**Comment by aallan** [comment]
I have no objection to this, and I think you'll find that some of the errata are referenced in the text in `NOTE` blocks in the relevant sections. I'll add an internal Jira to do so for all of them, although it's going to be a matter of availability of people time to get it done. There is a really long list nice-to-haves right now, sitting behind a bunch of need-to-do things.
