### ISSUE TITLE
I2C Default GPIO Pins TYPO in Pinout

### ISSUE THREAD

**Issue by kevindawson** [raspberrypi/pico-feedback#174]
In **raspberry-pi-pico-python-sdk.pdf**

- Section 3.6 
  - Table 2. Default I2C pins
    - I2C0 SCL Pin 9
    - I2C0 SDA Pin 8

![Pico-R3-A4-Pinout](https://user-images.githubusercontent.com/1690861/124968228-43bc0100-e01d-11eb-8c80-26f1983b901c.png)

Your Pinout should follow your SDK

first highlighted in [#7476](https://github.com/micropython/micropython/issues/7476) 

You need to Correct your Pinout Diagram

**Comment by aallan** [comment]
> Your Pinout should follow your SDK

It does, the default pins are shown for the C SDK. 

> You need to Correct your Pinout Diagram

We do not. The pinout diagram is **not** Python-specific. That said, the default Python I2C pins are indicated correctly; with GP8 as an I2C0 SDA(physical pin 11), and GP9 as an I2C0 SCL (physical pin 12). I don't know, or at least I can't remember, why those pins got picked for the Python port.

**Comment by kevindawson** [comment]
@JamesH65 any thoughts

**Comment by JamesH65** [comment]
I think thinking is so important. But apart from that, as @aallan is in charge of technical documentation at pi, no.
