### ISSUE TITLE
Update OpenOCD build instructions for Windows

### ISSUE THREAD

**Issue by maxgerhardt** [raspberrypi/pico-feedback#178]
As reported in https://github.com/raspberrypi/picoprobe/issues/3, the compile instructions at https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf, Appendix A, Build OpenOCD, Windows, fail to mention the very criticial fact that 
1. You should but put a `libusb-1.0.dll` file in the same folder as `openocd.exe`, as it is as dependency of the program. Otherwise it might randomly find this DLL somwhere in the `PATH` of the system of whatever version. Same goes for the `libhidapi-0.dll` when using the non-picoprobe branch (for CMSIS-DAP etc.)
2. Using the latest DLL version (1.0.24.11584) at https://github.com/libusb/libusb/releases will lead to a runtime error (segmentation fault). The previous version (1.0.23.11397), or as reported by others the latest master version, does not have this problem.
3. It seems weird to me that no `make install` is executed, but `openocd.exe` is run from the.. `src/` folder. For me, I did a `mkdir openocd_installed` and `make install DESTDIR=/home/$USER/openocd/openocd_installed` to get a redistributable packaged version of OpenOCD.

**Comment by maxgerhardt** [comment]
Note that I've opened https://github.com/libusb/libusb/issues/954 to have them do a new release. But even if they do, there should be a big exclamation mark there saying 1.0.24 is faulty.

**Comment by maxgerhardt** [comment]
In the LibUSB issue I was also able to find out that using Zadig to load **WinUSB** drivers instead of libusb-win32 does **not** lead to a crash with the latest 1.0.24 version of `libusb-1.0.dll`. So if the Raspberry Pi foundation's instructions had instead said WinUSB in the `Install Picoprobe driver (only needed on Windows)` chapter, the issue could have been avoided. 

![grafik](https://user-images.githubusercontent.com/26485477/126023347-6592fdd4-c3b0-4968-a59a-35298acde942.png)

Per linked issue a new release is also targeted 'soon' (and current master works too with libusb-win32 drivers), but due to shortage of maintainers it's a bit unsure.

EDIT: One of the maintainers of libusb again [urges](https://github.com/libusb/libusb/issues/954#issuecomment-881788560) that WinUSB instead instead of libusb-win32 is used because of better support.

**Comment by maxgerhardt** [comment]
..still no change. The documentation at page 62 still points to LibUSB istead of WinUSB. Is anybody having a look at this?

**Comment by JamesH65** [comment]
It is in hand.

**Comment by maxgerhardt** [comment]
After no documentation changes for a year, the libusb issues were resolved by the libusb devs, see [here](https://github.com/raspberrypi/picoprobe/issues/3#issuecomment-1132810855).
