### ISSUE TITLE
Getting Started With Pico C/C++ PDF - Typo 

### ISSUE THREAD

**Issue by adamlm** [raspberrypi/pico-feedback#18]
I believe there is a typo in Section 4.5. See "Hello World" UART output (page 14).

> Alternatively if you dragged and dropped the `hello_usb.uf2` binary, then the "Hello World" text will be directed to UART0 on pins GP0 and GP1.

The binary should be `hello_serial.uf2`.

**Comment by aallan** [comment]
Yes it should! Fixed in repo, will be fixed in the PDFs on next release. Many thanks.
