### ISSUE TITLE
Repeated "macros" heading definitions for PIO

### ISSUE THREAD

**Issue by matiasilva** [raspberrypi/pico-feedback#183]
![image](https://user-images.githubusercontent.com/23108156/127329671-dcd92864-c235-4256-8d9f-848bd0c3cf80.png)

4.1.15.3 - pg 141

**Comment by aallan** [comment]
Presume this is in the "[Raspberry Pi Pico C/C++ SDK](https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf)" book?

**Comment by lurch** [comment]
Thanks, will be fixed in the next PDF release of the databooks.
