### ISSUE TITLE
RP2040 datasheet issue table 164, page 143

### ISSUE THREAD

**Issue by mhinner** [raspberrypi/pico-feedback#19]
RP2040 DS error report:
https://datasheets.raspberrypi.org/rp2040/rp2040_datasheet.pdf

Bottom table 164 @ page 143; has addr 0x20000000 twice, the second should say 0x20000010 in my opinion.

**Comment by Wren6991** [comment]
Thank you for the report, this was already fixed upstream and will appear in the next docs release (should be today)
