### ISSUE TITLE
RTS/CTS pins missing from Pico pinout

### ISSUE THREAD

**Issue by rhulme** [raspberrypi/pico-feedback#193]
The RP2040 datasheet and SDK manual both show the possible UART RTS/CTS pins but they're not marked on the Pico pinout or in the same image in the Pico datasheet.  Presumably it would make sense to include them alongside TX and RX?

**Comment by aallan** [comment]
Possibly. But I decided to leave them off the pinout diagram for clarity due to the (relatively) little use the RTS/CTS pins get.

**Comment by rhulme** [comment]
OK, I suppose that's fair enough.

I don't know why it took me so long to think to look in the pinmux tables.  I saw the `uart_set_hw_flow` function in the SDK and read the _"UART hardware flow control"_ chapter in the datasheet and for the life of me couldn't work out how it should work in practice!  I think I was maybe searching for 'nUARTRTS' rather than just simply 'RTS'

**Comment by aallan** [comment]
I'll take a look at how I can make it clearer next time I revise things. Possibly I'll throw a `[NOTE]` block in the Getting Started guide where UART is first introduced.
