### ISSUE TITLE
MacOS installation

### ISSUE THREAD

**Issue by danielo515** [raspberrypi/pico-feedback#195]
Hello
I just succesfully installed the SDK on my macos. After figuring out the steps is quite easy but it took me a good 2 or 3 hours to figure it out, and I think it will be nice if in the future others can use that time to code actual projects 😄
So my suggestion is to include a MacOS section on the getting started pdf.

This are the stesp I followed:

## Gather dependencies:

```
brew tap PX4/homebrew-px4
brew update
brew install gcc-arm-none-eabi
```

## Get the SDK

I just cloned it into a path and then added it to my local environment variables (I have a specific file for this, so this may vary by user)

```bash
git clone -b master https://github.com/raspberrypi/pico-sdk.git ~/pico-sdk
echo "export PICO_SDK_PATH=~/pico-sdk" >> ~/.bash_profile # this can be different for you
```

## Install VSCode and the CMake extension

![image](https://user-images.githubusercontent.com/2270425/137917242-b99328d6-1c4e-4df5-bb18-7e95d44d2b43.png)

## Select the proper compiler on VSCode

![image](https://user-images.githubusercontent.com/2270425/137917386-9d08055c-fdab-4ea6-ba0b-53740bd117df.png)

Optionally configure the right import paths on the C/C++ extension:
![image](https://user-images.githubusercontent.com/2270425/137917626-7ed4839f-5090-4b4d-819e-651f3567d4cb.png)

Does it look good?

**Comment by lurch** [comment]
Do the instructions in section 9.1 of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf no longer work and/or need updating? :green_apple:

**Comment by aallan** [comment]
> Do the instructions in section 9.1 of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf no longer work and/or need updating? 🍏

Worked for me as recently as last week.

**Comment by danielo515** [comment]
> Do the instructions in section 9.1 of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf no longer work and/or need updating? 🍏

Let me check them, because I already read that PDF file and I didn't noticed there is a macos installation steps

**Comment by danielo515** [comment]
Ok. I totally missed that 9.x section, my bad. I have to say that that didn't expected it that late on the manual, after running examples and compiling some projects, I expected all installations one after the other.
As a last feedback, if you are willing to take it I would say:
 - Pointing to step 2.1 at the end of the 9.x step can be confusing because after 2.1 because steps 2.2 and 2.3 are linux specific, and the 9.1 note said that you can continue with all the steps from 2.1, and for mte that includes 2.2 and 2.3
 - I would recommend to include some notes about setting absolute paths (using home and/or `~`) for setting the environment variables and about setting those env variables on `.profile` files. This will help with future projects and makes it more friendly when you have to start your own projects

Feel free to close this issue.
Thanks
