### ISSUE TITLE
XIP_IRQ not explained in the RP2040 datasheet

### ISSUE THREAD

**Issue by tabemann** [raspberrypi/pico-feedback#196]
While reading the RP2040 datasheet, I saw the IRQ labeled XIP_IRQ listed amongst the IRQ's supported by the RP2040, but from further reading I saw no explanation whatsoever of the IRQ, much the less how to use it. Could the datasheet be updated to give some background on and explanation of this IRQ? Thanks.

**Comment by lurch** [comment]
Perhaps `XIP_IRQ` is the "combined interrupt request" mentioned in section "4.10.7. SSI Interrupts" in https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf ? :man_shrugging:

**Comment by liamfraser** [comment]
Andrew is right. It is the IRQ for the DW_apb_ssi used in the XIP block. I.e. might be useful if you were running from RAM and using the qspi pins for talking to a qspi normally not in XIP mode. Basically everyone uses qspi as boot flash but we could explain this.

**Comment by lurch** [comment]
> but we could explain this.

Thanks for volunteering Liam :laughing:

**Comment by liamfraser** [comment]
This will be fixed in an upcoming docs release
