### ISSUE TITLE
I2C Bus Clear Feature Confusion

### ISSUE THREAD

**Issue by fivdi** [raspberrypi/pico-feedback#199]
Section 4.3.13. of the [RP2040 Datasheet](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) is titled "Bus Clear Feature" and explains how the DW_apb_i2c supports the bus clear feature. This leads the reader to believe that the hardware Bus Clear Feature supported by the DW_apb_i2c is available on the RP2040. However, this is not the case as the Bus Clear Feature isn't actually enabled in silicon on the RP2040. The DW_apb_i2c configuration parameter for the Bus Clear Feature is called **IC_BUS_CLEAR_FEATURE** and it is set to 0x0 as can be seen [here](https://github.com/raspberrypi/pico-sdk/blob/1.3.0/src/rp2040/hardware_regs/include/hardware/regs/i2c.h#L49) meaning that the Bus Clear Feature is not available in hardware.

This discrepancy results in confusion, for example, see https://forums.raspberrypi.com/viewtopic.php?t=322970

It would probably be best to remove section 4.3.13. from the RP2040 Datasheet.

**Comment by aallan** [comment]
As noted at the start of section 4.3 on I2C is third-party documentation from Synopsys — included in the datasheet with permission — as Synopsys IP was used to implement the I2C peripheral in RP2040. I'll add an internal ticket to look into removing this section from the published datasheet.
