### ISSUE TITLE
Typographic formatting issues in RP2040 Datasheet

### ISSUE THREAD

**Issue by lonetech** [raspberrypi/pico-feedback#2]
build-date: 2021-01-21 build-version: fcd04ef-cl2.ean

Avoid breaking tables that would fit on one page over two. Examples: 
1.4.2 Pin Descriptions
1.4.3. GPIO Functions
(Those are right after each other, with a little text before GPIO functions, so the latter may not be so easy. Table 2 also relates to Table 3.)
2.1.1.2. Bus Performance Counters
2.1.5. List of Registers
2.2.1. Summary
2.19.2. Function Select table 289 (please just put a page break before heading 2.19.)

Avoid breaking headings from the contents of their section. Examples:
1.1. Why is the chip called RP2040?
1.4.1. Pin Locations
2.1.5. List of Registers
2.2.1. Summary
SIO: DIV_REMAINDER Register page 48-49
SIO: INTERP1_BASE1 Register page 53-54
SIO: INTERP1_PEEK_FULL Register page 54-55

Actually, just put a style sheet rule in that level 2 headings can't start on the bottom third of a page unless they fit in that page, like 1.2. This would help layout of 1.1, 1.3, 1.4, 2.5, 2.8, 2.15, 2.4 (an egregious example of split table!) etc. 

Never put a heading on the bottom of a page, like 4.1.2. 

Avoid splitting small sections, like most of the register descriptions. These frequently have a table which would make far more sense together with the three preceding chunks (heading, offset, description). 

Terrible example: SIE_STATUS register, table is so long it has to be split, but that's no excuse for putting all the non-table text on an earlier page - *including* the table legend in the left margin! That table descriptor should probably be on every page holding the table, certainly not on none!

**Comment by aallan** [comment]
Hey! The PDF documentation is automatically generated directly from asciidoc source. However the register tables are actually generated directly from the underlying RTL source for the chip, and the source code is automatically pulled in from the pico-sdk and pico-examples repos at document build time. 

That means there are a lot of moving parts in the generation of the PDF documentation. There are some problems with formatting as a result, mostly to do with page breaks in tables or code blocks. There is an internal list of known PDF template problems and all of the issues you've raised are already on the list. We're hoping the address these eventually.
