### ISSUE TITLE
Using i2c0 and i2c1 simultaneously

### ISSUE THREAD

**Issue by smdjeff** [raspberrypi/pico-feedback#200]
I assumed that since there are two i2c_inst_t that 
i2c_init() could be called twice - one for each.
But it seems to result in a lockup.

How does one run both i2c at the same time?

**Comment by lurch** [comment]
Yes, AFAIK that should work - doesn't appear to be anything in https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_i2c/i2c.c#L34 that modifies any global state outside of the `i2c_inst_t` that you pass in. Could you provide some example code please?

@kilograham Should this issue be moved to `pico-sdk` ?

**Comment by smdjeff** [comment]
Agreed
