### ISSUE TITLE
RP2040 Datasheet equates vs. Pico SDK equates

### ISSUE THREAD

**Issue by RealProgrammers** [raspberrypi/pico-feedback#201]
I have run into a difficulty. I have noted that the register names in the datasheet are totally different to the equates in the SDK. Since I am developing a low-level application, I'm using the datasheet all the time BUT the equates file does not match the datasheet.

It also means that reverse-engineering the SDK just to get the parts I need (for conversion into assembly language) is very difficult indeed since I cannot refer to the datasheet to understand what is going on.

I can understand that most people will choose to use C/C++ but I need to use 100% assembly language so I can write an MP2/MP3/MP4/ACELP decoder for the device. I presume that this would be useful to a LOT of people working on the Pico but it does appear that nobody has really considered use assembly language programmers.

I don't mean to moan. Without a doubt it's the best ARMV6t-based system to develop an audio decoder but as you can imagine, without a 32-bit x 32-bit -->64-bit multiply instruction, it takes 17 instructions so I need every cycle I can get so that people wishing to add the decoder to their project won't find out that it's taking 90% of the CPU time!

**Comment by kilograham** [comment]
As of SDK 1.3.0 (released last week) there is a cross reference from hardware_structs headers as used by the SDK functions to the raw register names in hardware_regs which have the same name as in the datasheet. If u use and IDE you should just be able to click thru from one to the other.

and yes, i write lots of code in assembly!

**Comment by lurch** [comment]
Can you give an example of where register-names in the datasheet are different to the equivalent in the SDK? The "register sections" in the RP2040 datasheet and some of the SDK headers are auto-generated, so things should match up fairly well?
By "equates file" are you referring to the `#define`s in the header files, or something else?

**Comment by aallan** [comment]
This seems to have been resolved by SDK 1.3.0 but never closed, so closing now.
