### ISSUE TITLE
Problem with sdk 1.3 and C++ error in ~/pico/pico-sdk/src/rp2_common/pico_platform/include/pico/platform.h

### ISSUE THREAD

**Issue by glimpit** [raspberrypi/pico-feedback#206]
After updating to pico sdk 1.3 my C++ project failed to build. On investigation I found the problem was with the following lines in
~/pico/pico-sdk/src/rp2_common/pico_platform/include/pico/platform.h

#if defined(__GNUC__) && __GNUC__ <= 7
#define __force_inline inline __always_inline
#else
#define __force_inline __always_inline
#endif

Changing this to
#define __force_inline __always_inline

fixed the problem.
Using the project generator to create a new vscode C++ project also show up this problem as the generated C++ project does not build.

**Comment by lurch** [comment]
Duplicate of https://github.com/raspberrypi/pico-sdk/issues/659 ?

**Comment by aallan** [comment]
Quite possibly!

**Comment by glimpit** [comment]
I agree it is a duplicate of raspberrypi/pico-sdk#659 and has been fixed on #650
