### ISSUE TITLE
DMA: RING_SIZE and reading WRITE_ADDR

### ISSUE THREAD

**Issue by jannic** [raspberrypi/pico-feedback#208]
I'm reading strange values from WRITE_ADDR while using DMA with RING_SIZE > 1.

According to the documentation, RING_SIZE works like a bit mask on the bits to be written while incrementing the address.
So, e.g. with a RING_SIZE of 4 I expect a sequence like 0x2003fb00, 0x2003fb04, 0x2003fb08, 0x2003fb0c, 0x2003fb00, ....
But if I actually read back the value from the WRITE_ADDR register, I sometimes get values slightly before the expected range, in the given example values like 0x2003faf4, 0x2003faf8, 0x2003fafc.

The DMA itself seems to work as expected (data is written to the expected memory rang, and the memory addresses outside the expected range are not affected).

Is there something else to be considered when reading the WRITE_ADDR register?

(Already asked this question at https://forums.raspberrypi.com/viewtopic.php?t=323813, but didn't get a reply.)

**Comment by Wren6991** [comment]
Oh -- looks like this is a hardware bug.

When you read from `WRITE_ADDR` or `READ_ADDR`, the DMA subtracts the number of in-flight transfers times the transfer size from the actual live register value, to avoid telling you that an address has been read/written when it is actually still in-flight in the DMA's bus pipeline.

This logic does not take nondefault increment modes into account, so gives odd values when `RING_SIZE != 0` or when increment is disabled.

You should still get sensible values by reading `TRANS_COUNT`.

**Comment by Wren6991** [comment]
Thanks for reporting this, I'll add an errata entry.

**Comment by jannic** [comment]
Thanks for the quick answer. One remark regarding `RING_SIZE > 0 && RING_SIZE <=4`: I'm quite sure I saw the same behavior with larger RING_SIZE (IIRC 13, can check in case it matters).

**Comment by Wren6991** [comment]
> Thanks for the quick answer. One remark regarding `RING_SIZE > 0 && RING_SIZE <=4`: I'm quite sure I saw the same behavior with larger RING_SIZE (IIRC 13, can check in case it matters).

Yes, that was wrong, I did edit my comment once I realised!

**Comment by jannic** [comment]
Oh - you already edited your answer. :-)

**Comment by Wren6991** [comment]
![image](https://user-images.githubusercontent.com/1298595/143488345-cd61d0f8-1c9d-444e-9479-6053ff9bd6a3.png)

This will appear in the next docs release. Congratulations on the first DMA erratum

(edit: though it will correctly say that trans_count decrements, rather than incrementing)
