### ISSUE TITLE
Raspberry Pi Pico Python SDK rshell port given as dev/serial0 not /dev/ttyACM0

### ISSUE THREAD

**Issue by ddwwcc** [raspberrypi/pico-feedback#21]
Raspberry Pi Pico Python SDK v1.1 Section 4.2  Using rshell

The string to start rshell is given as:
' rshell --buffer-size=512 -p /dev/serial0'
which I believe should be:
 'rshell --buffer-size=512 -p /dev/ttyACM0'
The first method does not work for me, the second does.

**Comment by aallan** [comment]
Yup. You're right. Fixed upstream, will appear in next documentation release.
