### ISSUE TITLE
cannot open source file pico/stdlib.h or hardware/spi.h

### ISSUE THREAD

**Issue by GitbyGit** [raspberrypi/pico-feedback#211]
I am trying to set up a new project folder for an SPI communication example, but I am running into this error of the two libraries. In the first image you'll notice my file set-up. The second picture is my M file set-up as well. the .vscode sets to SDK path which is correct.

<img width="1440" alt="Screen Shot 2021-12-07 at 10 23 45 PM" src="https://user-images.githubusercontent.com/35300870/145147930-3395ac85-99bb-4dfd-8f7c-9cbcea1111bc.png">

<img width="1440" alt="Screen Shot 2021-12-07 at 10 26 02 PM" src="https://user-images.githubusercontent.com/35300870/145148142-1b53d3ab-6ba1-4dfc-b780-4d6f972fa80a.png">

<img width="1440" alt="Screen Shot 2021-12-07 at 10 26 09 PM" src="https://user-images.githubusercontent.com/35300870/145148153-1f60edab-d456-4429-8a44-43bd5343ad6b.png">

**Comment by lurch** [comment]
Does the project actually build? I suspect that might just be an "editor warning" rather than a "build warning"?
IIRC there _is_ a way to fix that by telling the editor about your include-paths - perhaps @JamesH65 remembers how?
Alternatively, things might work more smoothly if you use https://github.com/raspberrypi/pico-project-generator ? :man_shrugging:

**Comment by GitbyGit** [comment]
Here is the output when building the project folder.

<img width="1440" alt="Screen Shot 2021-12-08 at 10 27 00 AM" src="https://user-images.githubusercontent.com/35300870/145245517-a02a538e-eb79-4e08-a43f-250d34079982.png">

**Comment by aallan** [comment]
> Here is the output when building the project folder…

These are warnings from VSCode, not the compiler. While the Raspberry Pi Pico SDK is compatible with VSCode, it is in fact our recommended IDE, we aren't really in a place to provide support for VSCode-specific issues. This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. Sorry.

**Comment by brianlmerritt** [comment]
The issues of squiggly lines are fixed in projects generated by pico-project-generator, so I am adding here in case someone else stumbles on this.

In the file `c_cpp_properties.json` add the following content

```
{
    "configurations": [
      {
        "name": "Linux",
        "includePath": [
          "${workspaceFolder}/**",
          "${env:PICO_SDK_PATH}/**"
        ],
        "defines": [],
        "compilerPath": "/usr/bin/arm-none-eabi-gcc",
        "cStandard": "gnu17",
        "cppStandard": "gnu++14",
        "intelliSenseMode": "linux-gcc-arm",
        "configurationProvider" : "ms-vscode.cmake-tools"
      }
    ],
    "version": 4
  
}
```
