### ISSUE TITLE
Corrupt i2c data when using Arrays or Pointers in main.cpp--using C C++ SDK

### ISSUE THREAD

**Issue by zaheeroz** [raspberrypi/pico-feedback#213]
Hi,
I have a c file imu.c where I get data from i2c (IMU). I call that module in main.cpp file.
Everything is fine untill I start using the IMU data in the main.cpp file.
When I start using arrays or pointers declared in the main.cpp, the data I get from i2c gets unstable. 
I am not sure is it memory problem or what. The file as a whole is about 100-800kb depending what I comment.
I am using c arrays or eigen vectors in main.cpp. The arrays or Eigen vector pass the data correctly, but when I see the IMU data graphically it is not stable once I start using arrays/vectors or pass a pointer to a function.  
Here get data from imu:
data=imuDataGet();
here data is a struture
soon after I get the data if I declare an array like
int aa[2]; 
aa[0]= 33;
int aab=aa[0];
printf("  %d    %f   ", aab, rpRateBFCMD(0));

the data is no more stable. when i comment assigning data or
accessing array the data gets stable.
I tried volatile and compiler optimization switches.
volatile doesnt do any good. Optimization switches doesnt fix
the issue but the data get a bit better.

Hope someone would understand whats going on. Thanks

**Comment by aallan** [comment]
This seems to be the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the documentation.
