### ISSUE TITLE
"CMake BuildConfiguration" appendix needs an example/clarification

### ISSUE THREAD

**Issue by guruthree** [raspberrypi/pico-feedback#215]
Appendix C "CMake Build Configuration" currently gives Table 27 "CMake configuration variables" without any indicator of how to use these.

Trying to learn more, googling "cmake variable" brought me to "[cmake-variables(7)](https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html)" and "[set](https://cmake.org/cmake/help/v3.0/command/set.html)", so I expected `set(PICO_STDIO_UART 0)` in CMakeLists.txt to be appropriate, but this is not the case. Later in the appendix `pico_set_binary_type(target type)` is given in a TIP as a way to set something that looks at a glance the same type of information as shown in Table 27, but is actually completely different.

Searching through the SDK further, PICO_BOARD is shown used in Appendix D "Board Configuration" as `cmake -D"PICO_BOARD=myboard" ..`, -D being the cmake flag for "Create or update a cmake cache entry." It appears to me then that the contents of Table 27 are not regular CMake variables, but CMake *cache* variables, which aren't treated the same. The way to set cache variables in CMakeLists.txt in a way they will be honoured when changed is `set(PICO_STDIO_UART 0 CACHE BOOL "" FORCE)`.

I suggest the following changes to Appendix C:
* A TIP be added after Table 27 "These can be specified as arguments to cmake when calling it from the build/ directory, e.g. `cmake -DPICO_STDIO_UART=0 ..`
* If Table 27 are not all CMake Cache Variables, adding a column to indicate this or separating them out into two (or more as appropriate) tables.
    * Edit the caption of Table 27 from "configuration variable" to "cache variable", unless they're not all cache variables. This would help clarify that the difference between these configuration options and those in the following sub-section. Everything in Appendix C is a configuration variable, but not all configuration variables are cache variables.
* Add a sub-section heading after "Configuration Parameters" reading "CMake Cache Variables" or increase the heading of "Control of binary type produced (advanced)" by one to help signal to the reader that while these two things look similar at first glance, they are not the same.

**Comment by aallan** [comment]
Fixed in the documentation. Will be present in the next release.
