### ISSUE TITLE
Datasheet bootrom code mismatch for _memset4

### ISSUE THREAD

**Issue by Sizurka** [raspberrypi/pico-feedback#217]
The code assigned to `_memset4` in the ROM looks like [`'S', '4'`](https://github.com/raspberrypi/pico-bootrom/blob/ef22cd8ede5bc007f81d7f2416b48db90f313434/bootrom/bootrom_rt0.S#L168) while the datasheet lists it as `'M', '4'`.  The bootrom matches the [Pico SDK](https://github.com/raspberrypi/pico-sdk/blob/2062372d203b372849d573f252cf7c6dc2800c0a/src/rp2_common/pico_bootrom/include/pico/bootrom.h#L26) so this only comes up when implementing directly from the datasheet.

Still, it tripped me up for a few hours trying to track down why non-SDK use wasn't working, so it would be nice to have the datasheet corrected.

**Comment by lurch** [comment]
ping @kilograham for confirmation. The relevant part of [RP2040 datasheet](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) seems to be "2.8.3.1.2. Fast Bulk Memory Fill / Copy Functions" on page 162.

**Comment by aallan** [comment]
Checked with Nick. @Sizurka is correct. I'll fix up the datasheet now. Fix will be in the next public release! 😄
