### ISSUE TITLE
Improve punctuation for channel_config_set_dreq() doc

### ISSUE THREAD

**Issue by blippy** [raspberrypi/pico-feedback#219]
The description for channel_config_set_dreq() is confusing to read in the PDF. 

Instead of
> Sources for TREQ signals are internal
(TIMERS) or external (DREQ, a Data Request from the system). 0x0 to 0x3a → select DREQ n as TREQ 0x3b → Select
Timer 0 as TREQ 0x3c → Select Timer 1 as TREQ 0x3d → Select Timer 2 as TREQ (Optional) 0x3e → Select Timer 3 as
TREQ (Optional) 0x3f → Permanent request, for unpaced transfers.

use a better layout, e.g.

> Sources for TREQ signals are internal
(TIMERS) or external (DREQ, a Data Request from the system). 0x0 to 0x3a → select DREQ n as TREQ  
**,**
> 0x3b → Select Timer 0 as TREQ
**,**
> 0x3c → Select Timer 1 as TREQ,
**,**

etc. (The limitation of github prevents me from making a proper formatting suggestions.)

**Comment by aallan** [comment]
Ah, I see. The API chapter in that book, along with the [API micro-site](https://raspberrypi.github.io/pico-sdk-doxygen/), are both autogenerated from the [Doxygen](http://www.doxygen.nl/) comments in the Pico C/C++ SDK. It would be a lot of effort to fix the formatting in the PDF documentation, and we're a small team and have to prioritise. I'll take a note internally, but it's unlikely this will get fixed. Sorry.

**Comment by blippy** [comment]
Why not just put commas in the C code description? It's a 5-minute fix. The changes will get propagated to the PDF automatically.

**Comment by aallan** [comment]
> Why not just put commas in the C code description? It's a 5-minute fix. The changes will get propagated to the PDF automatically.

Because we're a small team, and there are always hundreds of small quality of life fixes, and this isn't at the top of the list to look at for anyone. If you're interested in getting it resolved you could go over to the [raspberrypi/pico-sdk](https://github.com/raspberrypi/pico-sdk) repo and submit a PR?

**Comment by lurch** [comment]
This is where that particular piece of doxygen-markup appears: https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_dma/include/hardware/dma.h#L162
And this is how it renders on the micro-site: https://raspberrypi.github.io/pico-sdk-doxygen/group__channel__config.html#ga7c5a515cf1cfc6a8889464250b1e375b (using Doxygen's native HTML output)
