### ISSUE TITLE
2 DMA pacing timers are missing from headers and register listings

### ISSUE THREAD

**Issue by tannewt** [raspberrypi/pico-feedback#22]
Source code only has two pacing timers.

**Comment by tannewt** [comment]
Sorry, the error is in the datasheet on page 94 version b4f84f3-dirty.

**Comment by Wren6991** [comment]
Thanks, I checked and there are two timers in hardware (the datasheet is correct) but the headers are generated with the wrong parameter

**Comment by Wren6991** [comment]
Now also fixed on sdk `develop` branch, thanks for the report @tannewt

**Comment by tannewt** [comment]
Ooooh even better! Thank you!
