### ISSUE TITLE
Clarify Section 5.3 regarding openOCD and picoprobe

### ISSUE THREAD

**Issue by ObligedTester** [raspberrypi/pico-feedback#220]
Hello,

I think it would really add value to the "getting started guide" if it was mentioned that in order to use picoprobe, we need the commandline argument "interface/picoprobe.cfg".

In the text it only mentions "... like Picoprobe in Appendix A, we would specify a difference interface here"

if "picoprobe.cfg" was added there directly it would save a lot of time.

**Comment by aallan** [comment]
With the updated CMSIS compatible picoprobe software and the arrival of the Debug Probe. I think this is outdated now.
