### ISSUE TITLE
Datasheet: ADC: INTF INTS etc registers described identically.

### ISSUE THREAD

**Issue by rewolff** [raspberrypi/pico-feedback#225]
Datasheet RP2040, ADC, chapter 4.9. 
All INTx registers have an identical description. I understand the copy-paste, but someone forgot to adapt the descriptions a bit. 

(no need to explain things to me: I can figure it out if I need it but I don't need it at the moment. But it'd be nice to have it corrected for the rest of the readers in due time. ... )

**Comment by lurch** [comment]
Huh?
 * INTR says "Description: Raw Interrupts" (page 592)
 * INTE says "Description: Interrupt Enable" (page 593)
 * INTF says "Description: Interrupt Force" (page 593)
 * INTS says "Description: Interrupt status after masking & forcing" (page 593)

Could you explain what you mean in more detail please? (and if possible include page-numbers or screenshots)

**Comment by rewolff** [comment]
It's the bit description that is copy-pasted: This bit triggers....

**Comment by aallan** [comment]
There are only so many ways to word things? I'm not sure what you're getting at, we're describing the same thing, so it's worded the same way?

**Comment by lurch** [comment]
I think that behaviour is not specific to just the ADC, but applies to _all_ our "standard" interrupt INTR / INTE / INTF / INTS registers. The bit-description is describing what that particular interrupt corresponds to.
And those registers are all auto-generated from the same "source string", it's not a simple "lazy copy & paste".

**Comment by rewolff** [comment]
Sorry. I thought that the bit description for other peripherals did say stuff like "write one to clear this bit" with the bit descriptions. Now I can't find it anymore.
