### ISSUE TITLE
Minor Typo in Raspberry Pi Pico C/C++ SDK

### ISSUE THREAD

**Issue by adamlm** [raspberrypi/pico-feedback#23]
In Section 2.5.2. Return Codes and Error Handling
> Additionally most of the calls to `assert` are disabled by default for code/size performance (even in debug buidls [*sic*]);

Should be 
> Additionally most of the calls to `assert` are disabled by default for code/size performance (even in debug builds);

**Comment by Wren6991** [comment]
Thanks, fixed upstream, will appear in next release
