### ISSUE TITLE
Assigning more than 4 state machines or any quantity in both PIO0 and PIO1 results in PIO hang

### ISSUE THREAD

**Issue by cseatec** [raspberrypi/pico-feedback#230]
(This issue is based upon the same issue I posted in the Micropython respository  at [this link](https://github.com/micropython/micropython/issues/8513).  I am not sure if I should have posted it here instead since it may not be a Micropython issue and could be something else.)

Using Micropython and a Raspberry Pi Pico (RP2040), I am using the PIO state machines to generate PWM signals. At first, using 4 state machines assigned to IDs 0-3 (PIO0) works fine.  Also, if I assign the 4 state machines to IDs 4-7 (PIO1), that also works fine. But, as soon as I assign a 5th state machine to ID 4 (in PIO1) along with assigning the other 4 to IDs 0-3 (in PIO0), all the state machines in both PIOs won't run and hang up. _I later found that with even 2 state machines assigned in total, if I assign one to ID 0 (in PIO0) and assign the second to ID 4 (in PIO1), that still results in the same hang issue._  Simply changing the state machine IDs back to a pair in the same PIO with no other code changes makes it work again. It would seem that the  assignment of any quantity (min of 2, max of 8) of state machines across both PIO0 and PIO1 results in a hang condition for all PIOs.

Based upon what was mentioned in a [similar issue topic](https://github.com/micropython/micropython/issues/6961) in the Micropython repository, I made sure that none of the state machines access the same GPIO pins. I even tried spreading out the pins across both banks of the GPIO. That did not work either. I then tried making sure that the state machines in PIO0 and the ones in PIO1 use separate assembly code segments (so that both PIOs weren't trying to gain access to the same code in the 32-inst memory bank). That also made no difference since I believe both PIOs have their own, separate 32-inst memory banks shared between their 4 respective state machines.

I actually now need to use more than 4 state machines in a project I am working on, so I need to somehow get past this apparently limitation issue and be able to invoke the use of all 8 state machines.  Does anyone know what is going on with this?

**Comment by cseatec** [comment]
Well, this turned out to be my error.  I was using IRQs to synchronize all state machines, thinking that IRQ0 as set by state machine ID=0 was visible to state machine IDs 5-7. As it turns out, each PIO has 8 _separate_ IRQ flags.  That is, IRQs 0-7 as set and read by state machines IDS 0-3 have nothing to do with nor are visible by state machine IDs 5-7.  State machine IDs 5-7 have their own set of 8 IRQs, also numbered 0-7.  I was able to resolve the problem by instead using wait pin instruction to synchronize all 8 state machines.

Sorry for the false alarm.

**Comment by lurch** [comment]
> That also made no difference since I believe both PIOs have their own, separate 32-inst memory banks shared between their 4 respective state machines.

Yep, PIO0 and PIO1 are each an entirely separate instantiation of the PIO hardware block.

> As it turns out, each PIO has 8 separate IRQ flags. That is, IRQs 0-7 as set and read by state machines IDS 0-3 have nothing to do with nor are visible by state machine IDs 5-7.

Note that Section 3.4.9 of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf says "IRQ flags 4-7 are visible only to the state machines; IRQ flags 0-3 can be routed out to system level interrupts, on either of the PIO’s two external interrupt request lines, configured by IRQ0_INTE and IRQ1_INTE."

(also, I believe the "state machine IDs 5-7" is a MicroPython-specific abstraction)
