### ISSUE TITLE
Documentation for PIO: add clarification of MOV from PINS

### ISSUE THREAD

**Issue by Tails86** [raspberrypi/pico-feedback#234]
For the datasheet and SDK documentation under the MOV PIO instruction (currently under 3.4.8 in both), I suggest a note for source of PINS that the word copied from PINS will be ALL pins starting from PINCTRL_IN_BASE set in the config and wrapping around. 

I had forgotten that the range is not specified for sm_config_set_in_pins. It took me a while to understand why checking X after `MOV X, PINS` was not working as expected, and I needed to first `MOV OSR, PINS` before shifting out the number of bits I desired into X. MOV looks like the only read from PINS where a bit count is not explicitly given with the command.

Thank you for your time in considering this.

**Comment by lurch** [comment]
Does section 3.5.6.2. of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf answer your question?

**Comment by Tails86** [comment]
This is more of a request to add a note in the documentation to remind the reader that the MOV command copies all pin values from the PINS source (since it is the only read from PINS where a bitcount isn't provided with the command)

**Comment by Wren6991** [comment]
I added this note at the bottom to 3.4.8:

![image](https://user-images.githubusercontent.com/1298595/166654375-079a6090-16b5-40e3-a33a-1d1a2f6ebfdb.png)

If you feel like this clarifies things, it will appear in the next docs release.

**Comment by lurch** [comment]
Thanks Luke. Just for completeness, is a similar comment warranted for `MOV PINS, src`? Or is that not needed because of `PINCTRL_OUT_COUNT`?

(Hah, it's never occurred to me before, but `MOV PINS, PINS` might actually be a useful thing to do if you have different `IN` and `OUT` pin mappings :slightly_smiling_face: )

**Comment by Wren6991** [comment]
I'd assumed that was okay, since the out mapping has a count

**Comment by Tails86** [comment]
Yes, I think that will help out a lot. Thank you for hearing me out :)
