### ISSUE TITLE
How to understand pio irq flag lower 4 can masked into pio's interrupt request line.

### ISSUE THREAD

**Issue by eathard** [raspberrypi/pico-feedback#236]
"IRQ flags are state bits which can be set or cleared by state machines or the system. There are 8 in total: all 8 are visible
to all state machines, and **the lower 4 can also be masked into one of PIO’s interrupt request lines**, via the IRQ0_INTE and
IRQ1_INTE control registers. ",datasheet document say that. but I can not understand how to bind the pio irq flag to arm cortex M0+ irq interrupt line. And how to build a interrupt sevices function to deal with the pio irq flag . Can anyone help me?

**Comment by lurch** [comment]
You _might_ be able to glean some useful code-snippets from https://github.com/raspberrypi/pico-examples/search?q=irq&type=code , although there's probably no single example doing everything that you ask for.
Have a look also at section 2.3.2 of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf

Have a look at https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__irq.html and https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__pio.html#gaa90877ab7991e4b8bdea9d43ffb783db

And if you haven't already, you should definitely ask for help at https://forums.raspberrypi.com/viewforum.php?f=143
