### ISSUE TITLE
HW feature request: PIO IRQs as DREQ sources 

### ISSUE THREAD

**Issue by esky-software** [raspberrypi/pico-feedback#240]
Wiring PIO IRQs as (also) DREQ signals would add a significant new capability to PIO, especially in terms of interaction with other peripherals.

Currently, the only way PIO can trigger a DMA transfer is via the data FIFOs.  A PIO application that wants to trigger a data transfer to/from another peripheral - for example, to start a SPI transfer or PWM channel as a result of PIO activity, or to snapshot the Timer value into a memory buffer - has little option but to use an ISR.  Issuing a DREQ instead allows such actions to occur without processor involvement.

Ideally, setting the IRQ would automatically pulse the DREQ - failing that, the PIO program would need to manually pulse the IRQ (set then clear).

**Comment by arg08** [comment]
Note that the function asked for (PIO to kick off DMA to a third peripheral) can already be achieved by using two DMAs: first DMA takes DREQ from the PIO and either throws the word away and chains to the 2nd DMA, or writes to a trigger register in the 2nd DMA and starts it that way.  Sure, the proposed enhancement would slightly reduce latency and jitter, but you've got some of each of those even with the enhancement.

Another possible enhancement the same general category would be linking IRQs in the two PIO blocks - at the moment, there's really no good way to link timing between them, options being use of DMA (but that adds jitter that isn't inherent in the problem), or using GPIOs just to signal between the PIOs leaving the pin open (which works OK but most designs are short of GPIOs at the best of times, so giving up a pair for this purpose is painful).

**Comment by lurch** [comment]
> Another possible enhancement the same general category would be linking IRQs in the two PIO blocks - at the moment, there's really no good way to link timing between them

Section 3.4.9.2 of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf says "IRQ flags 4-7 are visible only to the state machines; IRQ flags 0-3 can be routed out to system level interrupts, on either of the PIO’s two external interrupt request lines, configured by IRQ0_INTE and IRQ1_INTE." ~~so (AIUI) you can use these external IRQ lines to communicate between the two PIO blocks? (or is that only an "output" from each PIO block, and not also an "input"?)~~
EDIT: Just been informed by a colleague "No, those IRQ outputs just go to the processor".

**Comment by arg08** [comment]
That's the issue - they can be routed _out_ of the PIO block to the CPU interrupts, but there's no route back in for anything outside (in particular, the other PIO block) to feed IRQ _in_ to the PIO.
(your edit came in literally as I pressed the button!)

**Comment by aallan** [comment]
These sorts of enhancements would need silicon changes, so are very unlikely to happen. I'll log the feedback on the internal ticket system.
