### ISSUE TITLE
Inconsistency in autopull pseudocode vs autpull overview in datasheet

### ISSUE THREAD

**Issue by jakewins** [raspberrypi/pico-feedback#245]
Sorry if this is not the right place to report this, please let me know if this should go somewhere else.

I'm writing an emulator for the PIO state machines, and I think the documented stalling behavior of `OUT` with autopull enabled is ambiguous.

The RP2040 datasheet says, in the bullet list under `3.2.4. Stalling`, that the PIO may stall for:

> An OUT instruction when autopull is enabled, OSR has reached its shift threshold, and the TX FIFO is empty

Implicitly I take this to mean that if the TX FIFO *isn't* empty, the `OUT` would pull from FIFO and execute. 

However, the psuedocode in `3.5.4.2. Autopull Details` says that it *always* will stall if the pull threshold is reached, independent of if it was able to pull or not:

```
1 if osr count >= threshold:
2   if tx fifo not empty:
3     osr = pull()
4     osr count = 0
5   stall <--- should this be in an else branch?
6 else:
7   output(osr)
8   osr = shift(osr, out count)
9   osr count = saturate(osr count + out count)
10
11   if osr count >= threshold:
12     if tx fifo not empty:
13       osr = pull()
14       osr count = 0
```

**Comment by lurch** [comment]
This should probably go in https://github.com/raspberrypi/pico-feedback
(EDIT: Thanks Graham)

**Comment by aallan** [comment]
This sounds like a @Wren6991 question!

**Comment by Wren6991** [comment]
Good eyes, thanks for pointing this out. The pseudocode is correct, the overview text is wrong.

OUT will always stall when the OSR is empty, irrespective of FIFO status. If the TX FIFO is nonempty then the OSR will become nonempty on the _next_ cycle, due to the autopull. On the next cycle, the OUT will unblock because the OSR now has data for it to shift out.

The reason for this behaviour is that there is no path in the hardware which goes directly from the FIFO read port to the OUT destination in one cycle (for timing reasons). This decision doesn't affect steady state throughput, because the SM _can_ pop and OUT on the same cycle, it just can't _use_ the pop for an OUT on the same cycle. It does however add one latency cycle between the FIFO becoming nonempty, and the OUT unstalling.

I'll fix the overview text.

**Comment by Wren6991** [comment]
![image](https://user-images.githubusercontent.com/1298595/172889032-242aba6c-4486-4ad8-ace8-f5fc9648053d.png)

Here is the new wording. If you're okay with this then it will appear in the next docs release.

**Comment by jakewins** [comment]
Awesome, thank you! And bummer, I had taken the speculative branch that the pseudocode was wrong and implemented what the bullet list said :) 

I have one more similar thing that I just came across, I think, and sorry to pile that into this same issue, but since I have you on the line. 

In 3.4.2.2 around jmp conditions, it says 

>  010: X--: scratch X non-zero, post-decrement
>  100: Y--: scratch Y non-zero, post-decrement

Which I read as "the condition is true - the jmp will execute - if X/Y is non-zero *after* it's been decremented". 

But in the description just below in the same section, is says:

> The branch is conditioned on the initial value of the register, i.e. before the decrement took place: if the register is initially nonzero, the branch is taken

Am I just misunderstanding, or are those two - "non-zero, post-decrement" and "branch is taken if register is initially nonzero" - contradicting each other?

**Comment by Wren6991** [comment]
The wording of "post-decrement" was supposed to imply that the checked value is the value before the decrement is performed (so the decrement is after the checked value is sampled). Analogous to

```c
// Post-decrement operator in C
do {
...
} while (x--);
```

As opposed to

```c
// Pre-decrement operator in C
do {
...
} while (--x);
```

So I think the datasheet is correct, I have just always struggled to word it in a way that is clear and unambiguous.

**Comment by Wren6991** [comment]
Oh -- I see the problem. I think you are parsing it as

> if (x, post-decrement) is nonzero

And the intended parse is

> if (x is nonzero), post-decrementing x

Maybe I can improve this.

**Comment by Wren6991** [comment]
How about

> 010: X--: scratch X non-zero, and decrement X after the check
> 100: Y--: scratch Y non-zero, and decrement Y after the check

**Comment by lurch** [comment]
> How about
> 
> > 010: X--: scratch X non-zero, and decrement X after the check
> > 100: Y--: scratch Y non-zero, and decrement Y after the check

That would probably also fix #150 too :slightly_smiling_face:

**Comment by Wren6991** [comment]
Oh, nice. Their suggested wording

> scratch X non-zero, prior to decrement

Is cleaner IMO, so I will use that.

**Comment by lurch** [comment]
Thanks, will be fixed in the next PDF release of the databooks.
