### ISSUE TITLE
Typo in the RP2040 datasheet

### ISSUE THREAD

**Issue by JeremyGrosser** [raspberrypi/pico-feedback#250]
In the text of Figure 72, the field named `CDM` should be `CMD`

**Comment by lurch** [comment]
For future reference; when we're sufficiently not-busy to have time to fix tasks like these:
![Screenshot from 2022-06-30 23-32-14](https://user-images.githubusercontent.com/476186/176789702-d401a9a0-d585-4668-a6b4-3afea4cce612.png)

**Comment by aallan** [comment]
Fixed in the documentation. Will be present in the next release.
