### ISSUE TITLE
There is no data in hello_usb example

### ISSUE THREAD

**Issue by Moon-Haze** [raspberrypi/pico-feedback#255]
I test the pico 's uart/usb. I  write code  according to the example. But I don't receive data using serial's software.
I use WSl to build the project. Does the problem  occur in WSL? I also don't receive data using the hello_usb example.
```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.15)
include($ENV{PICO_SDK_PATH}/external/pico_sdk_import.cmake)
project(pico_camke_test C CXX ASM)

set(CMAKE_C_STANDARD 11)

pico_sdk_init()

add_executable(${PROJECT_NAME} main.c)

pico_add_extra_outputs(${PROJECT_NAME})

pico_enable_stdio_usb(${PROJECT_NAME} 1)
pico_enable_stdio_uart(${PROJECT_NAME} 0)

target_link_libraries(${PROJECT_NAME} pico_stdlib)
```
```
// main.c
#include <stdio.h>

#include "pico/stdlib.h"

int main() {
#ifndef PICO_DEFAULT_LED_PIN
#warning blink example requires a board with a regular LED
#else
    const uint LED_PIN = PICO_DEFAULT_LED_PIN;
    gpio_init(LED_PIN);
    gpio_set_dir(LED_PIN, GPIO_OUT);
    stdio_init_all();
    while (true) {
        gpio_put(LED_PIN, 1);
        printf("LED ON \r\n");
        sleep_ms(250);
        gpio_put(LED_PIN, 0);
        printf("LED OFF \r\n");
        sleep_ms(250);
    }

#endif
}
```

**Comment by lurch** [comment]
Are you sure you've connected to the right COM port? See https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf for detailed instructions.

**Comment by Moon-Haze** [comment]
> Are you sure you've connected to the right COM port? See https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf for detailed instructions.

Yes. I look this in the Device Manager.

**Comment by lurch** [comment]
Please carefully follow the instructions in the getting-started-guide (i.e. build _without_ using WSL) and let us know if it's still not working?
When you say "I also don't receive data using the hello_usb example" was that a version of hello_usb you built yourself using WSL, or using the https://datasheets.raspberrypi.com/soft/hello_world.uf2 binary?

**Comment by Moon-Haze** [comment]
> Please carefully follow the instructions in the getting-started-guide (i.e. build _without_ using WSL) and let us know if it's still not working?
> When you say "I also don't receive data using the hello_usb example" was that a version of hello_usb you built yourself using WSL, or using the https://datasheets.raspberrypi.com/soft/hello_world.uf2 binary?

Thank you. I use my built using the WSL.I will test the release binary file to test.

**Comment by Moon-Haze** [comment]
> Please carefully follow the instructions in the getting-started-guide (i.e. build _without_ using WSL) and let us know if it's still not working?
> When you say "I also don't receive data using the hello_usb example" was that a version of hello_usb you built yourself using WSL, or using the https://datasheets.raspberrypi.com/soft/hello_world.uf2 binary?

I test this formal binary file, but I also receive data. Dose the problem occur in Windows OS?  Dose the pico's usb support Windows OS? Do I have to use the function uart to communicate the computer to the pico?

**Comment by lurch** [comment]
> I test this formal binary file, but I also receive data.

Huh? Do you mean you _didn't_ receive any data? Or you did receive data?

> Dose the pico's usb support Windows OS?

Other people have successfully had the USB-serial working with Windows (we **do** actually test all our software :wink: ).

I dunno what else to suggest at this stage, so you might get more detailed (and more rapid) help from https://forums.raspberrypi.com/viewforum.php?f=143 ?

**Comment by Moon-Haze** [comment]
> > I test this formal binary file, but I also receive data.
> 
> Huh? Do you mean you _didn't_ receive any data? Or you did receive data?
> 
> > Dose the pico's usb support Windows OS?
> 
> Other people have successfully had the USB-serial working with Windows (we **do** actually test all our software :wink: ).
> 
> I dunno what else to suggest at this stage, so you might get more detailed (and more rapid) help from https://forums.raspberrypi.com/viewforum.php?f=143 ?

Sorry. I don't receive any data.  The serial software used is popular in China. There is no problem  used it with Stm32 or Msp430/432. I will  look at the stage.
