### ISSUE TITLE
Blink an LED example (for MicroPython) needs change in pdf doc

### ISSUE THREAD

**Issue by felixgenicio** [raspberrypi/pico-feedback#259]
In the document https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf the section "2.5. Blink an LED" should be updated and instead of "led = Pin(25, Pin.OUT)" in the code example, it should be "led = Pin("LED", Pin.OUT)" in order to work properly in normal pico and pico w.

**Comment by aallan** [comment]
This is a duplicate, but I can't immediately find the issue it's a duplicate of (@lurch?). In any case, it's already on the list.

**Comment by felixgenicio** [comment]
Sorry, I searched before creating the issue by the word "LED" but cannot find any open issue related.

**Comment by lurch** [comment]
I suspect Alasdair was thinking of https://github.com/raspberrypi/pico-feedback/issues/260 , but that's to do with the C-SDK rather than MicroPython. So the issues are similar, but distinct :slightly_smiling_face:

**Comment by aallan** [comment]
Ah, yes I was!

**Comment by tobybroberts** [comment]
Will be fixed in the next PDF release.
