### ISSUE TITLE
Errors in pico-setup.sh

### ISSUE THREAD

**Issue by BruceMardle** [raspberrypi/pico-feedback#26]
In https://www.raspberrypi.org/documentation/pico/getting-started/ under the C/C++ tab, section "SDK setup", there's a button "Download Setup Script". I did that, ran the script and got errors on lines 29 and 35 ([[ not found) and 72 (Bad substitution). I don't know what (if anything) that breaks, but it probably needs fixing.

**Comment by aallan** [comment]
What platform did you run the script on? It's intended to be used on Raspberry Pi running a fully updated Raspberry Pi OS.

**Comment by BruceMardle** [comment]
Raspberry Pi 4 with up-to-date Raspberry Pi OS.

On Wednesday, 27 January 2021, 12:19:05 GMT, Alasdair Allan <notifications@github.com> wrote: 

What platform did you run the script on? It's intended to be used on Raspberry Pi running a fully updated Raspberry Pi OS.

**Comment by lurch** [comment]
Did you make the script executable with `chmod +x pico_setup.sh` ?

**Comment by BruceMardle** [comment]
Yes.

On Wednesday, 27 January 2021, 12:53:00 GMT, Andrew Scheller <notifications@github.com> wrote: 

Did you make the script executable with chmod +x pico_setup.sh ?

**Comment by aallan** [comment]
The sort of error you're getting looks like you might be trying to execute the script not in bash. Do you have a non-default shell?

**Comment by BruceMardle** [comment]
Nope.
It's a newish setup, so maybe [[ lives in a package that's not installed by default?

On Wednesday, 27 January 2021, 13:06:43 GMT, Alasdair Allan <notifications@github.com> wrote: 

The sort of error you're getting looks like you might be trying to execute the script not in bash. Do you have a non-default shell?

**Comment by aallan** [comment]
Are you running on Lite?

**Comment by lurch** [comment]
What does `/bin/bash --version` say?

**Comment by BruceMardle** [comment]
Ermm, I'm not sure. It started life as 2021-01-11-raspios-buster-armhf.zip (1,227,921,990 bytes), which didn't include the 'recommended' software (though I've installed some of it since).

On Wednesday, 27 January 2021, 13:18:25 GMT, Alasdair Allan <notifications@github.com> wrote: 

Are you running on Lite?

**Comment by lurch** [comment]
@BruceMardle I also ran pico_setup.sh on a fresh install of 2021-01-11-raspios-buster-armhf yesterday and didn't get any errors, so after some internal discussions we have got no idea what might be going wrong for you :confused: Are you able to reflash your SD card and start again afresh?

**Comment by BruceMardle** [comment]
Sorry for the delay.

$ /bin/bash --version
GNU bash, version 5.0.3(1)-release (arm-unknown-linux-gnueabihf)
(etc.)

I'm only vaguely interested in the Pico. (I've already got a PIC project and an FPGA project "on the go".) I think I'll wait till other people have sorted out the early bugs!


On Wednesday, 27 January 2021, 13:24:13 GMT, Andrew Scheller <notifications@github.com> wrote: 

What does /bin/bash --version say?

**Comment by aallan** [comment]
This problem hasn't been reported by any one else. 

We're happy to help with trying to diagnose your issue, but it's likely caused by local setup changes on your Raspberry Pi. To isolate your problem it the best course at this point would be to make a fresh installation of the OS on a new SD Card, and install on a clean system. Then try again.
