### ISSUE TITLE
Request for OTA bootloader

### ISSUE THREAD

**Issue by estrellar** [raspberrypi/pico-feedback#262]
OTA example for pico w.

**Comment by aallan** [comment]
Writing an over-the-air bootloader for Pico W isn't really adding an example, it's a serious infrastructure project. We're a small team and it's very unlikely we'll get around to it ourselves. However, you should go look around [the forums](https://forums.raspberrypi.com/viewforum.php?f=143&sid=0fa11313605d43190fc3369b630cc07d), I know there is some community interest in writing one.

**Comment by lurch** [comment]
Coincidentally, see https://github.com/raspberrypi/pico-sdk/issues/928

**Comment by usedbytes** [comment]
I spent my weekend porting over a bootloader I already wrote for regular Pico to use WiFi on Pico-W, see here:

https://github.com/usedbytes/picowota_blink (as referenced from #928)
