### ISSUE TITLE
help with testing iperf programs.

### ISSUE THREAD

**Issue by develone** [raspberrypi/pico-feedback#263]
https://github.com/develone/my-projects-docs/blob/master/pico-w/steps-iperf.txt

**Comment by aallan** [comment]
Hey there, we're a small team and don't really have the resources to do that. It's possible you could find someone to help you on [the forums](https://forums.raspberrypi.com/).

**Comment by lurch** [comment]
If you've not already seen it, you _might_ find https://github.com/raspberrypi/pico-examples/#pico-w-networking useful? :shrug:
