### ISSUE TITLE
state machine 

### ISSUE THREAD

**Issue by Yang123bing** [raspberrypi/pico-feedback#267]
there are two pio modules and 8 state machine in the rp2040,and where I can find the state machine's source code? I wanna know how the state machine works.

**Comment by JamesH65** [comment]
The state machines are HW blocks that execute PIO instructions. Those instructions are up to you to program.

See chapter three in this datasheet. https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf

**Comment by aallan** [comment]
The PIO state machine is part of the chip architecture, it's hardware not software. As James mentioned it's discussed in the RP2040 Datasheet, https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf.
