### ISSUE TITLE
Documentation (rp2040 data sheet): no "List of Registers" in Table-of-Contents entry for SIO

### ISSUE THREAD

**Issue by WestfW** [raspberrypi/pico-feedback#272]
Most of the "peripherals" in the the rp2040 datasheet include a sub-section "List of Registers" that shows up in the Table of Contents, and is thus easily findable from most PDF readers.

However, the SIO subsystem is grouped as a sub-section of the "Processor Subsystem", and presumably this extra level of nesting prevents the list of registers (section 2.3.1.7) from appearing in the table of contents, making it somewhat difficult to find.

It would be nice if either the ToC is allowed more depth so that the SIO ToR shows up, or perhaps SIO should be brought out as its own section instead of being grouped under "processor subsystem" - it really is more like the peripherals than the other functions described in section 2.3.  (alas, I guess that would renumber all of the following sections, making older references to the documentation be off.)

Workaround: The SIO section is pretty lengthy, so going to the next subsection ("Interrupts") and paging backwards is easier than paging forward from the start of the SIO section.

**Comment by lurch** [comment]
I agree that it's unfortunate that the "List of Registers" for SIO doesn't show up in the ToC. However getting the right "depth" of headers displayed in the ToC is a bit of a balancing-act; as you may have guessed the ToC is entirely auto-generated. If we increased the ToC-depth so that the SIO's List-of-Registers _did_ show up in the ToC, this would also include **lots** of other headers into the ToC, and this would make the ToC so long as to become unwieldy.

**Comment by WestfW** [comment]
> as you may have guessed the ToC is entirely auto-generated.

Yeah, I figured.  Are you sure that there isn't a way to explicitly add a ToC entry, bypassing the automation?  It seems like it would be a pretty common requirement (though I am not at all in touch with modern Document Preparation Tools.)

**Comment by lurch** [comment]
> Are you sure that there isn't a way to explicitly add a ToC entry, bypassing the automation?

Yes. https://docs.asciidoctor.org/asciidoc/latest/toc/

We spent some time juggling the ToC level before the release of the RP2040 and its documentation, and settled on the current value as the best compromise.

Although I've just done a bit of additional searching and found https://github.com/asciidoctor/asciidoctor-pdf/issues/2097 so we'll discuss internally if this is a feature we want to implement. (It's a feature only available in AsciiDoctorPDF 2.x, and we're also currently migrating our toolchain from AsciiDoctorPDF 1.x to AsciiDoctorPDF 2.x)
