### ISSUE TITLE
Getting started: page 19

### ISSUE THREAD

**Issue by blippy** [raspberrypi/pico-feedback#28]
In s5.4 (Use GDB ..., page 19) of the Getting started with Raspberry Pi Pico, it states:

```
cd ~/pico/pico-examples/build/hello_world
```

I think that should be

```
cd ~/pico/pico-examples/build/hello_world/serial
```

**Comment by Wren6991** [comment]
Thanks, there were a few other references in that book to when we only had a serial hello world program. Should all now be fixed upstream, will appear in the next release.
