### ISSUE TITLE
SDK-Documentation: Missing return in int main()

### ISSUE THREAD

**Issue by pingufreak** [raspberrypi/pico-feedback#282]
As in the subject, the examples doesn't return an int. But I think it's important, because I had issues with the usb-serial if not returning int.

**Comment by lurch** [comment]
_Very_ little detail in this issue, but I believe it relates to https://github.com/raspberrypi/pico-feedback/issues/283 ?

**Comment by aallan** [comment]
Duplicate of #283

**Comment by aallan** [comment]
If you have more information to add to this, please add it to #283.
