### ISSUE TITLE
Adding VSCode Pico-W-Go extension as alternative to Thonny to the Pico docs chapter MicroPython

### ISSUE THREAD

**Issue by paulober** [raspberrypi/pico-feedback#290]
Is it possible to list my Visual Studio Code extension (Pico-W-Go) as an alternative to Thonny in the Raspberry Pi Pico (W) documentation in the MicroPython chapter?

Pico-W-Go is a Visual Studio code extension designed to simplify and speed up the development of MicroPython projects for the Raspberry Pi Pico and Pico W boards.
More information can be found here: https://github.com/paulober/Pico-W-Go or in the wiki https://github.com/paulober/Pico-W-Go/wiki.

I thought that, since your documentation is very much designed to help beginners getting started with MicroPython microcontroller programming, it would be helpful for some of them to be able to use the editor they probably already know for programming.

The Visual Studio Code extension already has over 5.1 thousand downloads. I have already received constructive feedback, which helped me to improve the extension. I plan to continue to build on this in the future. The link to the Microsoft VS Code marketplace publication is as follows: https://marketplace.visualstudio.com/items?itemName=paulober.pico-w-go

(Just as a quick note concerning the contributing guidelines third party chapter: I was referred to this repository by a Raspberry Pi Foundation staff member with this request.)

**Comment by aallan** [comment]
We actually just had an email conversation internally about just this, and the answer is essentially, "Yes, that's on our list." 

We're having a bit of an internal toolchain rejig right now, but after that is done (a week or so) it's on the list of things that need doing in the near term.

**Comment by lurch** [comment]
@paulober Is it possible to also build your extension for Linux arm32? As I believe that would then allow it to also run on [32-bit Raspberry Pi OS](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit)?

**Comment by aallan** [comment]
Something like 85% of Raspberry Pi boards in the wild run 32-bit user space Raspberry Pi OS.

**Comment by paulober** [comment]
@aallan Happy to see that this has already been discussed internally and is planned.

@lurch I would like to. The reason why the extension is limited to specific architectures is the node serialport library and as you can see on their website and in my extension this dependency includes prebuilds also for linux armv6 and armv7 the 32-bit arm versions which will be used by a raspberry pi running in "32-bit mode" on the armv8 processors. I'm a bit confused that these are not working as some community members told me. 
I'm setting up a Pi4b in 32-bit and see what i can find out. I'll send an update on this once i figured it out.

**Comment by paulober** [comment]
@aallan @lurch Just published version [v2.1.3](https://github.com/paulober/Pico-W-Go/releases/tag/v2.1.3) which added support for armv7 (aka Raspberry Pi OS 32-bit on 3b+, 4b or 400).

**Comment by lurch** [comment]
> armv7 (aka Raspberry Pi OS 32-bit on 3b+, 4b or 400).

Also the Pi 2B and the Pi Zero 2 W :slightly_smiling_face:  https://www.raspberrypi.com/documentation/computers/processors.html

**Comment by paulober** [comment]
> > armv7 (aka Raspberry Pi OS 32-bit on 3b+, 4b or 400).
> 
> Also the Pi 2B and the Pi Zero 2 W 🙂 https://www.raspberrypi.com/documentation/computers/processors.html

True, should theoretically work just as well as on the other platforms, but unfortunately can't test this myself on these.

**Comment by paulober** [comment]
@aallan Any updates on this?

**Comment by aallan** [comment]
> @aallan Any updates on this?

Not really. The toolchain problems are now sorted, it's just time to sit down and write some documentation around it that's needed. It's on the list of things to do.

**Comment by ghollingworth** [comment]
Paul,

Will you please get in touch with me at gordon@raspberrypi.com

Gordon

**Comment by aallan** [comment]
Some information about the extension and using it with VSCode will be added in the next documentation release, which should happen this week.

**Comment by paulober** [comment]
> Some information about the extension and using it with VSCode will be added in the next documentation release, which should happen this week.

Happy to hear it. Will check the documentation every now and then.

**Comment by paulober** [comment]
@aallan 
Apologies for reaching out once more. I seem to be unable to locate the note regarding Pico-W-Go that you mentioned in the Raspberry Pi Docs on the website. Could you kindly assist me in finding it?
Thank you.

**Comment by aallan** [comment]
It's not on the website, it's in the PDF documentation, see Section 4.2 of https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf.

**Comment by paulober** [comment]
Hey @aallan,

Just wanted to give you a heads up on some changes to the extension:

1. The FTP-Server is removed - it was outdated. Instead, we now have a new Virtual FileSystem/Workspace integration into VSCode.
2. I renamed the extension to "MicroPico" to better match its focus on supporting MicroPython projects for Raspberry Pi Pico and Pico W boards. But the ID remains the same (for some time) `paulober.pico-w-go`
