### ISSUE TITLE
Wrong datasheet link for CYW43439

### ISSUE THREAD

**Issue by Ioan-Cristian** [raspberrypi/pico-feedback#294]
I don't know if this is the right place to report the following bug, so I apologize if I made a mistake.

In the datasheet of the Raspberry Pi Pico W (https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf), section 3.8, the link for the Infineon CYW43439 datasheet is wrong. Specifically, when I click on the link, I get a NOT_FOUND error. I think the datasheet can now be found at the following address: https://www.infineon.com/dgdl/Infineon-CYW43439-DataSheet-v03_00-EN.pdf?fileId=8ac78c8c8386267f0183c320336c029f

**Comment by aallan** [comment]
Yup. Looks like they've rearranged their website. I'll fix the link and it'll be updated in the next documentation release. Many thanks.
