### ISSUE TITLE
Pico W won't reboot when uf2 file dragged Windows

### ISSUE THREAD

**Issue by marcocrio** [raspberrypi/pico-feedback#299]
I guess this is a problem similar to the [ventura](https://github.com/ARMmbed/DAPLink/issues/982) issue (which I also encounter with on my mac) but it is happening on Windows 10 Pro version 20H2.

I've built the examples using the C/C++ SDK and I'm trying to flash the Blink example but every time I drag and drop the blink.uf2 (or any other uf2 file) the device won't eject or do anything. 
Something I've also noticed is that even if I plug in the pico, even if the bootsel is not pressed, it will get mounted as a hard drive. 

I also tried flashing through SWD using a [MAX32625PICO ](https://www.analog.com/media/en/technical-documentation/data-sheets/MAX32625PICO.pdf) which uses a DAPLink interface but I got the following error: 

> Error: Failed to connect multidrop rp2040.dap0

**Comment by lurch** [comment]
> Something I've also noticed is that even if I plug in the pico, even if the bootsel is not pressed, it will get mounted as a hard drive.

Sounds to me like either your BOOTSEL button is broken (i.e. perhaps it's being "pressed" when you think it isn't), your Flash is entirely empty, or you've got some other software already running on your Pico which is presenting itself as a virtual storage device? :man_shrugging: 
What file-contents do you see in the Pico's "hard drive"? 

And just to rule out any build-error with the UF2s you've built yourself, you can download pre-compiled UF2s from https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html#blink-an-led (note that the blink UF2 is different for Pico and Pico W).

**Comment by aallan** [comment]
There is no OS-level problem similar to that found in macOS Ventura for Windows 10. Sorry, but you're seeing something else.

**Comment by marcocrio** [comment]
> > Something I've also noticed is that even if I plug in the pico, even if the bootsel is not pressed, it will get mounted as a hard drive.
> 
> Sounds to me like either your BOOTSEL button is broken (i.e. perhaps it's being "pressed" when you think it isn't), your Flash is entirely empty, or you've got some other software already running on your Pico which is presenting itself as a virtual storage device? 🤷‍♂️ What file-contents do you see in the Pico's "hard drive"?
> 
> And just to rule out any build-error with the UF2s you've built yourself, you can download pre-compiled UF2s from https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html#blink-an-led (note that the blink UF2 is different for Pico and Pico W).

I would discard the BOOTSEL button issue as I've tried with two different new out of the box devices and both of them show the same issue. 
I see the following structure:
```
System Volume Information folder 
    IndexerVolumeGuid
    WPSSettings.dat
INDEX.HTM
INFO_UF2.TXT
```
I would lean more towards the option that a software is already running on the Pico but the fact that I tried on 2 out of the box PIcos would deter me from that idea. 

I guess the biggest clue is the fact that when I drop the uf2 file the device won't unmount itself. (I've tried dropping the blink_picow.uf2 file but still the device won't unmount) 

reading though the documentation I've noticed that the the picotool can be used to interact with the RP2040 while in 
BOOTSEL mode but to use it I need to install the libusb library which I will try next and see If I can get the device out of the BOOTSEL mode. I'll update with the results.

**Comment by kilograham** [comment]
Are these regular Picos, or some custom board?

It is acting like your binary is bad (the board will not reboot if it doesn't like the UF2, and indeed a bad binary written to flash may cause it to re-enter BOOTSEL mode without BOOTSEL pressed); try downloading a pre-built binary.

I'm sure there is a `blink.uf2` somewhere online, but you could try this at least (which wipes the flash, but should at least cause a reboot when dragged)

https://datasheets.raspberrypi.com/soft/flash_nuke.uf2

**Comment by marcocrio** [comment]
> 

They are regular Picos and I have tried to flash the pre-built binaries (both the blink.uf2 and the flash_nuke.uf2) and still no response

**Comment by lurch** [comment]
Strange. Do you have any kind of security or AV software running on your PC that might be interfering with writing the UF2 to Pico? Do "normal" USB Flash drives work okay for you? Do you have access to another PC that you might be able to test on?

**Comment by marcocrio** [comment]
> 

So I did a little research I found that indeed my computer has some security feature that encrypts USB drives. I tried on a different windows PC and I was able to flash the Pico.

**Comment by busslina** [comment]
Same issue here. Works okay when copied the UF2 file, but no on reboot. Any improvement on this issue? Any way to disable USB drive encryption?

**Comment by busslina** [comment]
I don't think it is because of Windows encrypting the USB drive. I did same operation through a Raspberry Pi 3b. Working once flashed, but not working on reconnected USB supply (no bootsel pressed).

**Comment by lurch** [comment]
What image are you flashing? Note that _some_ UF2s might only write their contents into RAM (and thus be lost after a power-down) rather than Flash.

**Comment by busslina** [comment]
@lurch I'm creating that image in Windows 10 with this CMakeLists.txt file:

```
set(APP_NAME "motion_sensor")

cmake_minimum_required(VERSION 3.13)

set(PICO_BOARD pico_w)

include(../pico-sdk/external/pico_sdk_import.cmake)

project(${APP_NAME} C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)

pico_sdk_init()

add_executable(${APP_NAME}
    src/motion-sensor.c
)

pico_enable_stdio_usb(${APP_NAME} 1)
pico_enable_stdio_uart(${APP_NAME} 0)

pico_add_extra_outputs(${APP_NAME})

target_link_libraries(${APP_NAME} pico_stdlib pico_cyw43_arch_none)
```

When using MicroPython it does works after reboot, so it seems you are right. Is there any way to make it persistent across reboots?

**Comment by lurch** [comment]
Hmm, this is where my knowledge runs out, so it might be worth opening a new issue at https://github.com/raspberrypi/pico-sdk rather than commenting on an already-closed issue in pico-feedback?

(EDIT: the default behaviour is for it to be persistent, you have to do extra steps if you want a RAM-only image)

**Comment by busslina** [comment]
Thanks @lurch. New issue: https://github.com/raspberrypi/pico-sdk/issues/1258

**Comment by busslina** [comment]
I resolved my issue. In my case it was my error. I was initiating the Wifi module (cyw43) in order to use the Onboard Led. Calling `cyw43_arch_init()` was working okay when flashing because the Pico was yet connected to the power supply. It was falling on reboots because this function was returning not success and I was closing my app in that case.

The solution is simple: `a)` to await an undefined amount of time (in my case I am lighting the LEDs for 3 seconds) or `b)` to execute that function without delay and retrying until success.
