### ISSUE TITLE
Micropython SDK documetation omission.

### ISSUE THREAD

**Issue by PeterOGB** [raspberrypi/pico-feedback#30]
Following  this forum post https://www.raspberrypi.org/forums/viewtopic.php?f=146&t=301081 ....
There doesn't seem to be any explanation in https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-python-sdk.pdf
that the PIO instruction "in" has to be written as "in_" .  It is only shown in passing as part of the SPI example.

**Comment by Wren6991** [comment]
Thank you for raising! Will make sure this is covered as part of #31.
