### ISSUE TITLE
Pico BOOTSEL mode stopped working randomly

### ISSUE THREAD

**Issue by raymondjxu** [raspberrypi/pico-feedback#300]
I wrote a bit of code (using the C/C++ SDK, not MicroPython) that broadcasts a Wi-Fi network and exposes some functionality with the GPIO. I've updated it many times over the past week, where BOOTSEL and dragging the .uf2 works perfectly fine. 

Unfortunately, starting today, disconnecting it from power, pressing BOOTSEL, connecting it via USB and releasing BOOTSEL doesn't work. It just boots into the normal code, which has the functionality of everything I uploaded yesterday night: remotely setting GPIO pins (one of the features that I added last night), for example, works perfectly fine if I use a multimeter to view the pin states.

I've also tried shorting TP6 to ground via a stripped wire in place of pressing BOOTSEL. That has no effect either. ``picotool`` doesn't work either, presumably since I never use the SDK's USB tools.

Any ideas what this could be caused by?

**Comment by aallan** [comment]
This is the sort of question you should be asking on the [forums](https://www.raspberrypi.org/forums/), so I’m closing this issue. But please follow up with further comments if you have specific questions about the [documentation](https://www.raspberrypi.org/documentation/).
