### ISSUE TITLE
Pico W PCB keepout for antenna

### ISSUE THREAD

**Issue by WojtaCZ** [raspberrypi/pico-feedback#308]
Would it be possible to add a PCB "footprint" specification for the pico W? Mainly the optimal dimensions of a ground pour keepout for the antenna to function propertly (if the pico W is mounted right on the PCB without heares).

**Comment by lurch** [comment]
See page 26 of https://datasheets.raspberrypi.com/rp2040/hardware-design-with-rp2040.pdf ?

@dp111 Should something suitable also be added to https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf ?

**Comment by WojtaCZ** [comment]
Sorry, missed the mention in "Hardware design with RP2040" - honestly, wouldnt expect it there....

It would certainly be great if it could be added in the pico W datasheet.

**Comment by aallan** [comment]
There will be a keepout diagram added to the Pico W datasheet in the new docs release.
