### ISSUE TITLE
Documentation Bug: C/C++ SDK book incorrectly describes PIO JMP

### ISSUE THREAD

**Issue by cadouthat** [raspberrypi/pico-feedback#315]
[https://datasheets.raspberrypi.com/pico ... -c-sdk.pdf](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf)
Page 59, the book states (regarding the PIO JMP instruction):
```
* 010: X--: scratch X non-zero, post-decrement
* 100: Y--: scratch Y non-zero, post-decrement
```
However, the JMP decrement conditions are actually "pre-decrement"

**Comment by lurch** [comment]
This was previously discussed in #150 and #245 - the wording is correct, but you have to "read it in the right way" :wink: 
We've already tweaked this for the RP2040 datasheet (see page 320 of https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf ) but we forgot to make the same change for the C/C++ SDK book. I'll make sue that happens before we next publish the PDFs.
