### ISSUE TITLE
Raspberry Pi Pico Python SDK: ADC value different in ADC(channel) vs ADC(Pin(#))

### ISSUE THREAD

**Issue by scruss** [raspberrypi/pico-feedback#318]
A forum user noted in [ADC channel number vs. GPIO pin number - Raspberry Pi Forums](https://forums.raspberrypi.com/viewtopic.php?t=348430) that these two initialization methods cause the ADC to return noticeably different values. Initializing by channel [leaves the pull-down enabled](https://forums.raspberrypi.com/viewtopic.php?p=2087648#p2087378), while initializing by pin does not. There is test code in the thread.

The documentation should use `ADC(Pin(#))` throughout for consistency. I'm not sure where that leaves the internal temperature sensor which is not normally assigned a pin number.

Associated MicroPython issue: [RP2040: ADC value different in ADC(channel) vs ADC(Pin(#)) · Issue #10947 · micropython/micropython](https://github.com/micropython/micropython/issues/10947)

**Comment by aallan** [comment]
This feels very much like a MicroPython issue to me. I'll keep an eye on it, and change the documentation if that's what's decided on their end. But, as you say, that leaves the ADC connected to the internal temperature sensor somewhat out on a limb. So just insisting that we use `ADC(Pin(#))` doesn't seem like a solution.

**Comment by aallan** [comment]
Not a documentation issue, so transferred to the `pico-feedback` repo.

**Comment by scruss** [comment]
> So just insisting that we use ADC(Pin(#)) doesn't seem like a solution.

Fair enough, but ADC(4) has always seemed to read too high to me, even when I have an accurate temperature sensor sitting on top of the chip. So maybe exposing the internal sensor via a Pin object may not be a bad idea.

There's a PR in for this already, so I hope it goes away soon

**Comment by lurch** [comment]
> ADC(4) has always seemed to read too high to me, even when I have an accurate temperature sensor sitting on top of the chip.

See my comment [here](https://github.com/micropython/micropython/issues/10947#issuecomment-1457840879). Do you get the same temperature reading using MicroPython as you do using the C SDK?

**Comment by aallan** [comment]
> > So just insisting that we use ADC(Pin(#)) doesn't seem like a solution.
> 
> Fair enough, but ADC(4) has always seemed to read too high to me, even when I have an accurate temperature sensor sitting on top of the chip. So maybe exposing the internal sensor via a Pin object may not be a bad idea.

The on-chip temperature sensor is very sensitive to errors in the reference voltage. If the ADC returns a value of
891 this would correspond to a temperature of 20.1°C. However, if the ADC reference voltage is 1% lower than 3.3V then
the same reading of 891 would correspond to 24.3°C. You would see a change in temperature of over 4°C for a small
1% change in reference voltage. Therefore if you want to improve the accuracy of the internal temperature sensor it
is worth considering adding an external reference voltage on the `ADC_VREF` (physical pin 35).

**Comment by aallan** [comment]
Peeking over the wall at micropython/micropython#10947 it looks like this has been, or will shortly be resolved.
