### ISSUE TITLE
Swap "digits" and "bytes"

### ISSUE THREAD

**Issue by whheydt** [raspberrypi/pico-feedback#32]
Pg. 119, hexadecimal balloon... "each digit contains two bytes..." should be "each byte contains two digits...".

**Comment by Wren6991** [comment]
Sorry, page 119 of which document? I just grepped through all of our document sources and I don't see this phrase. I also don't see it in any of the PDFs.

**Comment by aallan** [comment]
Could be "Get started with MicroPython and Raspberry Pi Pico" typo, so the Pi Press book rather than ours? @benevpi ?

**Comment by benevpi** [comment]
Yep it is. Thanks for the report. I'll get it sorted.

**Comment by aallan** [comment]
Closing then. Thanks for the report!
