### ISSUE TITLE
Some mistakes on raspberry-pi-pico-c-sdk.pdf

### ISSUE THREAD

**Issue by MrGreensWorkshop** [raspberrypi/pico-feedback#328]
There are some mistakes at page 41.  https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf
(I checked with the https://www.raspberrypi.com/documentation/pico-sdk/hardware.html)

```
wrong                              correct
pio_set_consecutive_pindirs   ->   pio_sm_set_consecutive_pindirs
sm_config_sideset_pin         ->   sm_config_set_sideset_pins
sm_config_out_shift           ->   sm_config_set_out_shift
pio_sm_enable                 ->   pio_sm_set_enabled
```

**Comment by aallan** [comment]
Not mistakes, but it looks like the API has drifted somewhat since the text was originally written.

**Comment by MrGreensWorkshop** [comment]
If there is no mistake, how should I call those? Would you correct me?
Please don't take it as I blame the person who wrote the document. We are all here to give people better documentation nothing else.

**Comment by lurch** [comment]
I think Alasdair meant that they weren't mistakes when the documentation was _originally_ written, but the API has been updated and the documentation hasn't yet been updated to match.

**Comment by aallan** [comment]
@nathan-contino After thanksgiving can you take a look at this one, it's page 42 in the [published](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf) version.

**Comment by aallan** [comment]
Fixed internally. Will be in the next documentation release.
