### ISSUE TITLE
is it possible to use and install the sdk without python

### ISSUE THREAD

**Issue by seropigeorgedev** [raspberrypi/pico-feedback#333]
I hate python it is the worst scripting language ever in my opinion but why do stupid sdk's like this need python they could just have used any other scripting language like bash sh, or lua idk but can anyone please help me install this sdk without the need of python :(

**Comment by aallan** [comment]
Sorry, that isn't possible.

**Comment by seropigeorgedev** [comment]
> Sorry, that isn't possible.

Well that is unfortunate sorry for my miss-behavior (i do think it is possible though but idk for sure) though I found  a replacement anyway so for people who also don't or can't use python...
