### ISSUE TITLE
Update macOS sections in "Getting Started with Pico" to talk about Intel and Apple silicon

### ISSUE THREAD

**Issue by neerajadsul** [raspberrypi/pico-feedback#335]
Document: Getting Started with Pico, 
Version 2.2 , 14-June-2023

For building OpenOCD on macOS Monterey, we need to install newer version of `texinfo` using `brew`.
After installation the `PATH` is appended with location:

```sh
$ export PATH="/usr/local/opt/texinfo/bin:$PATH"
```
However the **texinfo** `bin` directory is at `/opt/homebrew/Cellar/texinfo/7.0.3/bin`

Therefore correct path export should be as follows.

```sh
export PATH="/opt/homebrew/Cellar/texinfo/7.0.3/bin:$PATH"
```
The brew formula does mention path for macOS in celler. Hope I am not the only one getting the issue.
I can update the doc but not sure it is in this repository as the guide seems to be ISO style quality controlled.

**Comment by lurch** [comment]
This might be a difference between Homebrew on an Intel-silicon Mac, and Homebrew on an Apple-silicon Mac? ping @aallan

**Comment by aallan** [comment]
This is the difference between Intel and Apple silicon. I thought I'd updated the Mac sections with `NOTE` blocks, but apparently not. It's on the list.

**Comment by neerajadsul** [comment]
Ah, yes, it seems so. However, both seems to use the location `Cellar`. Thanks.

**Comment by aallan** [comment]
Yup, that's down to your Homebrew version. Earlier versions didn't have that. I'll get it updated.

**Comment by nathan-contino** [comment]
Fixed, because we've eliminated the need for to manually build OpenOCD in our upcoming release.
