### ISSUE TITLE
SDK 1.5.1 clock documentation error

### ISSUE THREAD

**Issue by matsobdev** [raspberrypi/pico-feedback#340]
There is CLOCKS_CLK_SYS_CTRL_AUXSRC_VALUE_ROSC_CLKSRC instead of CLOCKS_CLK_SYS_CTRL_AUXSRC_VALUE_XOSC_CLKSRC where it suppose to be (it looks like that at least): Examples >Clock example > Auxiliary Clock Sources > XOSC / clk_sys.

**Comment by aallan** [comment]
Sorry, I'm not entirely sure what the question is?

**Comment by matsobdev** [comment]
In the 1.5.1 SDK release page on Github, there is HTML documentation https://github.com/raspberrypi/pico-sdk/releases/download/1.5.1/sdk-1.5.1-html-doc.zip and in given location there are two `CLOCKS_CLK_SYS_CTRL_AUXSRC_VALUE_ROSC_CLKSRC` for `XOSC` and `ROSC`. Inside SDK there is `CLOCKS_CLK_SYS_CTRL_AUXSRC_VALUE_XOSC_CLKSRC` for XOSC, that is correct I suppose (my bad, it is also 2x ROSC).
![Screenshot 2023-08-01 at 17-30-19 Raspberry Pi Pico SDK hardware_clocks](https://github.com/raspberrypi/pico-feedback/assets/63716661/dddf4e22-1911-43df-897f-1741c3f9f111)

**Comment by aallan** [comment]
Ping @kilograham

**Comment by lurch** [comment]
If this is indeed a "bug", the same thing also occurs at https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#rpipe93dd39da7bd5b73a2e7
(look at the bottom two cells in the right-most column)
![Screenshot from 2023-08-01 16-39-19](https://github.com/raspberrypi/pico-feedback/assets/476186/e34604f7-0aca-4f2f-aae4-702eb298edcd)

ping @liamfraser (as IIRC he did a bunch of the clocks stuff)

**Comment by matsobdev** [comment]
`SDK\src\rp2_common\hardware_clocks\include\hardware\clocks.h` line `57` it is the same - just comment so no huge deal.

**Comment by lurch** [comment]
> `SDK\src\rp2_common\hardware_clocks\include\hardware\clocks.h` line `57` it is the same - just comment so no huge deal.

Ah yes, looks like https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2_common/hardware_clocks/include/hardware/clocks.h#L57 is the ultimate source of where all these generated-output-files are coming from.

**Comment by kilograham** [comment]
cc @liamfraser ; i assume this is just a typo, but haven't looked in detail

**Comment by lurch** [comment]
Yesh, looks like this was fixed by https://github.com/raspberrypi/pico-sdk/pull/1571 :slightly_smiling_face:
