### ISSUE TITLE
Update VSCode plugin information

### ISSUE THREAD

**Issue by aallan** [raspberrypi/pico-feedback#342]
Update the VSCode plugin information in Section 4.2 of [the MicroPython book](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf).

See #290. 

<img width="984" alt="Screenshot 2023-08-01 at 12 48 23" src="https://github.com/raspberrypi/pico-feedback/assets/53625/2bac7ea1-0ff3-421f-87d1-52b7a03d2cba">

**Comment by paulober** [comment]
> Update the VSCode plugin information in Section 4.2 of [the MicroPython book](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-python-sdk.pdf).
> 
> See #290.
> 
> <img alt="Screenshot 2023-08-01 at 12 48 23" width="984" src="https://user-images.githubusercontent.com/53625/257504986-2bac7ea1-0ff3-421f-87d1-52b7a03d2cba.png">

Correction: the ID remains the same: `paulober.pico-w-go` (for now)

**Comment by aallan** [comment]
@nathan-contino This needs poking at to find out where we are with this, since you're going to be installing things in any case this looks like a good one for you. It'd be nice to get a bit more around the VSCode option into the MicroPython book to balance our current coverage of Thonny.

**Comment by paulober** [comment]
Any updates on this?

**Comment by aallan** [comment]
We've been a bit distracted by [something else](https://www.raspberrypi.com/news/introducing-raspberry-pi-5/) for the last few months. Sorry.

**Comment by paulober** [comment]
> We've been a bit distracted by [something else](https://www.raspberrypi.com/news/introducing-raspberry-pi-5/) for the last few months. Sorry. 

I know, sorry, didn't want to annoy, just thought I might have overlooked the change again.

**Comment by aallan** [comment]
Not annoyed at all. We've just been… busy. There's a lot of things going on, and this (like anything that wasn't [Bookworm](https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/) or [Pi 5](https://www.raspberrypi.com/news/introducing-raspberry-pi-5/) related) has got backlogged. I'm hoping to start in on microcontroller stuff again next month.

**Comment by aallan** [comment]
Fixed in the documentation. Will be present in the next release.
