### ISSUE TITLE
GPIO line 24 seems to be disabled

### ISSUE THREAD

**Issue by thangnguyen-69** [raspberrypi/pico-feedback#347]
The original problem is here: 
https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/issues/74
The problem is that without calling the f_open, the GPIO24 line can still output 1. But after calling it, the GPIO 24 line will never be 1 again, even if i try to connect to bluetooth. 
The Pico W datasheet does not seems to talk about this , it only say GPIO24: OP/IP wireless SPI data/IRQ. And nothing more.
How should i proceed.

**Comment by kilograham** [comment]
GPIO24 is not broken out as a pin on Pico W, so setting it via other software seems a bit pointless, and yes doing so may break the communication with the WiFi chip.

**Comment by thangnguyen-69** [comment]
That's weird, because I read the source for the SD library, but it does not really set the GPIO24 specifically, only setting up SPI interface, and IRQ. So I want to ask if there is any other accidental way that may disable the GPIO24(by disable i mean the GPIO24 will not return 1 anymore)? Or..
Where can i find documentation, or code in the SDK that affect this GPIO24?

**Comment by lurch** [comment]
You might get a quicker response asking for help at https://forums.raspberrypi.com/viewforum.php?f=143

**Comment by thangnguyen-69** [comment]
> You might get a quicker response asking for help at https://forums.raspberrypi.com/viewforum.php?f=143

I did actually, the post has been idle in the pico SDK forum thread for 6 days: https://forums.raspberrypi.com/viewtopic.php?t=355486
The new post can be found here:
https://forums.raspberrypi.com/viewtopic.php?t=355658
