### ISSUE TITLE
Typo - Getting started... p51:  pip3 install -U cmsus-svd

### ISSUE THREAD

**Issue by maseman** [raspberrypi/pico-feedback#35]
getting-started-with-pico.pdf

Release 1.1

build-date: 2021-01-26
build-version: b4f84f3-dirty

Page 51

9.3.1. Using openocd-svd

$ pip3 install -U cms**u**s-svd

should be

$ pip3 install -U cmsis-svd

**Comment by Wren6991** [comment]
Thanks, fixed upstream, will appear in next docs release
