### ISSUE TITLE
Pico C/C++ SDK: Incorrect CMake target name for TinyUSB device lib

### ISSUE THREAD

**Issue by fkjagodzinski** [raspberrypi/pico-feedback#358]
This issue is about one of the official PDF guides for Pico -- [_Raspberry Pi Pico C/C++ SDK_](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf
), tagged as `build-date: 2023-06-14`, `build-version: a6fe703-clean`.

Section _2.3.6. TinyUSB Port_

> The `tinyusb_dev` or `tinyusb_host` libraries within the SDK can be included in your application dependencies in `CMakeLists.txt` to add device or host support to your application respectively.

The correct CMake target name for TinyUSB device is [`tinyusb_device`](https://github.com/raspberrypi/pico-sdk/blob/6a7db34ff63345a7badec79ebea3aaef1712f374/src/rp2_common/tinyusb/CMakeLists.txt#L40), not `tinyusb_dev`.

**Comment by aallan** [comment]
Fixed in next docs release.
