### ISSUE TITLE
USB: BUFF_STATUS register is readonly in the datasheet, but readwrite in the SDK

### ISSUE THREAD

**Issue by Tiwalun** [raspberrypi/pico-feedback#36]
The `BUFF_STATUS` register is marked as readonly in the datasheet (page 414), but as readwrite in the C SDK headerfile
`src/rp2040/hardware_structs/include/hardware/structs/usb.h`.

I assume the SDK is correct, because the status bits are reset by the USB sample code.

**Comment by liamfraser** [comment]
PR https://github.com/raspberrypi/pico-sdk/pull/100 fixes this. This will also turn up in the next datasheet release.
