### ISSUE TITLE
Inconsistent units in watchdog_enable() documentation

### ISSUE THREAD

**Issue by wluker** [raspberrypi/pico-feedback#360]
In the SDK documentation the parameter `delay_ms` in function `watchdog_enable` is stated to be in milliseconds, but a max value of 0x7fffff corresponding to 8.3 seconds would indicate that `delay_ms` is actually in microseconds. What is the correct unit?

**Comment by lurch** [comment]
Fixed by https://github.com/raspberrypi/pico-sdk/pull/1567 ?

**Comment by aallan** [comment]
Looks to be!
