### ISSUE TITLE
Lowering RP2040/Pico power consumption guide

### ISSUE THREAD

**Issue by matsobdev** [raspberrypi/pico-feedback#361]
At forum, JamesH if I remember correctly, announced that kind of document quite time ago, which would be very useful I suppose. Is there any info about it? How far is it or if it is considered at all?

**Comment by matsobdev** [comment]
Actually, there is "Power switching RP2040 for low standby current applications", so closing

**Comment by lurch** [comment]
> Actually, there is "Power switching RP2040 for low standby current applications", so closing

...which is at https://pip.raspberrypi.com/categories/685-whitepapers-app-notes , for the benefit of anybody else that finds this issue in future :slightly_smiling_face:
