### ISSUE TITLE
pico-examples directory structure changes not reflected in the book.

### ISSUE THREAD

**Issue by Dygear** [raspberrypi/pico-feedback#363]
https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf

Page 6:
> To then build a basic example for Raspberry Pi Pico W that will scan for nearby wireless networks, you can do:
> ```bash
> $ cd pico_w/wifi_scan
> $ make
> PICO_SDK_PATH is /home/pi/pico-sdk
> PICO platform is rp2040.
> Build type is Release
> PICO target board is pico_w.
> .
> .
> .
> [100%] Built target picow_scan_test_background
> $```

Given the last block of text, we are in the **pico-examples/build**, but the directory structure for **pico-examples/build** has changed. It is no longer in the **cd pico_w/wifi_scan** directory. You now need to go to **cd pico_examples/pico_w/wifi/wifi_scan**.

Page 9:
> along with the lwipopts.h file needed by the lwIP stack.
> `$ cp ../pico-examples/pico_w/lwipopts_examples_common.h lwipopts.h`

The path **../pico-examples/pico_w/lwipopts_examples_common.h** is incorrect and should be **../pico-examples/pico_w/wifi/lwipopts_examples_common.h**. The change to add **wifi** to the path has caused some problems.

**Comment by aallan** [comment]
@nathan-contino When Thanksgiving is over can you take a look at this one and anything else that might have gotten moved around in the `pico-examples` repo in the "Getting Started" and "Connecting to the Internet" books.

**Comment by nathan-contino** [comment]
Done!
