### ISSUE TITLE
Mistake in python sdk in the PIO section

### ISSUE THREAD

**Issue by webdeb** [raspberrypi/pico-feedback#368]
Maybe this is just outdated, but there is no `sideset_pins` and `set_pins` argument for `@asm_pio` decorator. It should be init for both cases.

<img width="880" alt="Bildschirm­foto 2023-12-22 um 04 31 04" src="https://github.com/raspberrypi/documentation/assets/14992140/f6f39adf-ca89-4d7f-b6f2-805af9e0ccc9">

**Comment by lurch** [comment]
Looks like MicroPython must have renamed those parameters? https://docs.micropython.org/en/latest/library/rp2.html#rp2.asm_pio

**Comment by webdeb** [comment]
@lurch maybe, however, in the other passages of the pdf the author used the correct arg names.

**Comment by webdeb** [comment]
Oh, forgot to mention, that the StateMachine has also other arg names, `sideset_base` and `set_base`

**Comment by lurch** [comment]
@nathan-contino See also #142

**Comment by aallan** [comment]
Fixed in the documentation. Will be present in the next release.
