### ISSUE TITLE
PLL Post-Divider Enable Behavior

### ISSUE THREAD

**Issue by benjacam** [raspberrypi/pico-feedback#371]
Hello,

**Background**
 I am designing a system where multiple RP2040 must be synchronised to a common reference clock. Let's say the reference clock is 10MHz, the PLL VCO is running at 1000MHz and the post-dividers are set to 5 and 2 giving 100MHz FOUTPOSTDIV. My aim is for the 100MHz FOUTPOSTDIV on each RP2040 to be phase aligned (zero phase offset). 

For example, my product could be a 64-bit logic analyser using four RP2040 in parallel each sampling 16-bits - the sampling instants of each RP2040 must be the same to coherently sample the bus.

I have not prototyped anything yet, I'm trying to understand if RP2040 can meet the requirement by reading the the datasheet and SDK. Alternately, I could use a small FPGA, but I like the RP2040 and would prefer to use it if I can!

**Potential Problem**
The RP2040 PLL feedback is taken from the VCO output (_not_ post divider). Because of this, the FOUTPOSTDIV could rest at one of ten phases separated by 1ns. Note: whilst the VCO output is phase locked to the reference, the post-division outside the loop causes this phase ambiguity. 

**Question/Solution?**
To understand if the potential problem is real, I'd like to understand what happens in RP2040 when the post-dividers are enabled. After the CPU clears POSTDIVPD, to avoid the phase ambiguity, the VCO would need to wait until the next edge of the reference clock, and only then enable the dividers. This would need to happen without any possibility of meta-stability, which might cause a slip by one VCO cycle. Is it implemented like this, or does it simply enable the dividers on next VCO edge?

If the latter, are there any other options to achieve my aim? If I implemented a phase detector, is there any way to slip/nudge the phase of the post-dividers?

Thank you!

**Comment by aallan** [comment]
This honestly sounds involved enough that you potentially should be talking directly to our Applications Team, who can either help directly or point you at one of our Design Partners. Email applications@raspberrypi.com.
