### ISSUE TITLE
[Pi 5]: Does SDK Tool chain also work on Pi 5 

### ISSUE THREAD

**Issue by hasenradball** [raspberrypi/pico-feedback#373]
Hi,

I set up the SDK toolchain on my Raspberry Pi 4 and I am able to build and flash the Pi Pico via VScode perfectly.

Does the toolchain also work on the Pi 5?
I heard there was changes in gpio driver from Pi 4 -> Pi 5.

**Comment by lurch** [comment]
There's currently a couple of small wrinkles around debugging and serial-port access (see https://github.com/raspberrypi/pico-sdk/issues/1611 and the various issues it links to), but these should be fixed soon. The toolchain itself (i.e. building UF2 files) should be fine.

**Comment by peterharperuk** [comment]
Please stop using issues to ask questions. There's a forum here https://forums.raspberrypi.com/viewforum.php?f=144
