### ISSUE TITLE
Documentation for Pi Pico Debug Probe is out of date after name change

### ISSUE THREAD

**Issue by Swiftloke** [raspberrypi/pico-feedback#378]
### Problem: 
Appendix A of the Pi Pico Getting Started guide refers to flashing the ``picoprobe.uf2`` file if the user wants to use their Pi Pico as a debug probe for another Pi Pico. But this is now out of date after a recent [name change due to legal reasons](https://github.com/raspberrypi/debugprobe/commit/d0c03d2564fb6aa2cccfe9e08f48efe7e2463ace).

The change from ``picoprobe.uf2`` to ``debugprobe.uf2`` might be trivially understandable, but this is not in fact the correct solution. [According to the maintainers of that repo](https://github.com/raspberrypi/debugprobe/issues/119) one must *now* flash ``debugprobe_on_pico.uf2`` to the Pico. 

This makes the documentation invalid, since attempting to follow the directions now produces a Pico that does not act as a debug adapter.

### Suggestion:
The rename from ``picoprobe.uf2`` -> ``debugprobe_on_pico.uf2`` is confusing, especially since I imagine the majority of users won't be interested in flashing Raspberry Pi Debug Probes that already come with that firmware pre-installed. It should be renamed to ``debugprobe.uf2``, and the Raspberry Pi Debug Probe firmware should be renamed to ``debugprobe_official_hardware.uf2`` or similar. 

Whether or not the above suggestion is applied, the documentation should be updated to reflect the new file that must be flashed for a Pi Pico.

**Comment by nathan-contino** [comment]
The source code for that has already been updated, thanks for the reminder. Expect this file rename to go into effect that the same time as the other PDF improvements, when we next roll the PDFs out.

I will pass along the rename suggestion to TPTB; personally, I think it would be best to leave the `debugprobe.uf2` name behind entirely and exclusively use `debugprobe_on_pico.uf2` and something like `debugprobe_official_hardware.uf2` to make things as explicit as possible.
