### ISSUE TITLE
Suggestion: Include a simple PIO read example in the C/C++ documentation

### ISSUE THREAD

**Issue by ZodiusInfuser** [raspberrypi/pico-feedback#38]
I've been getting into PIO as I want to do some reading of data. After following the Chapter 3 documentation, I found it a leap in understanding from the output focused `hello_pio` and `ws2812` to the input focused `logic_analyzer` example, particularly as that focused on DMA.

As such, I would like to suggest that a simple example be included that is similar to hello_pio but for reading a pin (also more input examples in general, but that's a side issue).

I wrote this as a test that seems to work (but verify yourselves):

```
.program reader
loop:
    in pins, 1
    push
    jmp loop
 
% c-sdk {
 
static inline void reader_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = reader_program_get_default_config(offset);
 
    sm_config_set_in_pins(&c, pin);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, 0);
    pio_sm_init(pio, sm, offset, &c);

    pio_sm_set_enabled(pio, sm, true);
}
%}
```

This would then show that the setup is common to both examples
```uint offset = pio_add_program(pio, &reader_program);
uint sm = pio_claim_unused_sm(pio, true);
reader_program_init(pio, sm, offset, PIN);
```

And that to get data out of the SM you call `pio_sm_get(pio, sm);`. Could maybe have it toggle the onboard LED based on the pin state. Note, I haven't included anything about pull-up in that, as I am yet to look up what sm specific function to call.

Thanks

**Comment by aallan** [comment]
I think raspberrypi/pico-examples#43 closes this issue.
