### ISSUE TITLE
TBD and spelling in Hardware design with rp2350 

### ISSUE THREAD

**Issue by ekholm** [raspberrypi/pico-feedback#395]
https://datasheets.raspberrypi.com/rp2350/hardware-design-with-rp2350.pdf

Search for: capcitors

On page 7 there is a TBD on the inductor, still valid?
Page 9 " These resistors, R2 and R6" should be "These resistors, **R1** and R6"

**Comment by lurch** [comment]
ping @mike-stimson

**Comment by nathan-contino** [comment]
Fixed the typos, waiting for confirmation before I update the resistor references and TBD

**Comment by nathan-contino** [comment]
Paging @mike-stimson again :)

**Comment by mike-stimson** [comment]
Yeah, the resistor reference was wrong, whoops. TBD is still valid at the moment.

**Comment by nathan-contino** [comment]
Fixed the resistor reference. We'll update the TBD when we have something for you!
