### ISSUE TITLE
Broken links in Raspberry Pi Pico 2 Datasheet 

### ISSUE THREAD

**Issue by ekholm** [raspberrypi/pico-feedback#396]
At least on Page 5 section 1.1 Raspberry Pi Pico 2 design files

Links are broken -> 404

**Comment by lurch** [comment]
@ekholm I've transferred your issues, but in future please report problems with the PDF documentation to  https://github.com/raspberrypi/pico-feedback  - thanks!

**Comment by nathan-contino** [comment]
This has been fixed, new PDF should be rolling out soon.
