### ISSUE TITLE
Avoid pico-setup.sh running out of space

### ISSUE THREAD

**Issue by Hermann-SW** [raspberrypi/pico-feedback#4]
This might not be easy depending on which of the packages to be installed are already installed or not. But I did run multiple times into out of space, before I freed 1GB and then setup did complete successfully. So when pico-setup.sh starts, and it could determine that it will run out of space at start, that will avoid minutes of waiting and running out of space then.

**Comment by aallan** [comment]
Warning added in today's V1.1 release about the amount of space needed. Best we can do I think.

<img width="857" alt="Screenshot 2021-01-26 at 17 12 31" src="https://user-images.githubusercontent.com/53625/105879104-b1d5b400-5ff9-11eb-9816-3f727c9872b1.png">

**Comment by Hermann-SW** [comment]
Thanks, better than nothing.

**Comment by lurch** [comment]
Part of the problem is that even `apt` itself doesn't display a warning message if there's not enough free disk space - it just continues as normal and fails badly when it's unable to write anything more to disk!

**Comment by Hermann-SW** [comment]
Time for an issue against apt on that?

**Comment by lurch** [comment]
That's a problem for Debian to deal with, rather than Raspberry Pi. But feel free! :grinning:

**Comment by Hermann-SW** [comment]
I would -- but its not that easy.

apt on github does not allow to create issues:
https://github.com/Debian/apt

It is mirrored from here, but there a 0 issues at all:
https://salsa.debian.org/dashboard/issues?scope=all&utf8=%E2%9C%93&state=all

Strange ...

**Comment by lurch** [comment]
> apt on github does not allow to create issues:
https://github.com/Debian/apt

Try this: https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=apt
