### ISSUE TITLE
svd files rp2040.svd or RP2040.svd

### ISSUE THREAD

**Issue by ekholm** [raspberrypi/pico-feedback#402]
In "old" sdk the svd file was named rp2040, in latest sdk it's named RP2040.svd.
Is that an omission or change in naming convention?

**Comment by lurch** [comment]
It's a deliberate change - [`RP2040.svd`](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2040/hardware_regs/RP2040.svd) and [`RP2350.svd`](https://github.com/raspberrypi/pico-sdk/blob/develop/src/rp2350/hardware_regs/RP2350.svd) are now the new names.

**Comment by kilograham** [comment]
ARM's newer tooling complains with the lower case
