### ISSUE TITLE
Getting started wiht Raspberry Pi Pico-series - default PICO_BOARD build inconsistency pp. 35 and 39

### ISSUE THREAD

**Issue by drankinatty** [raspberrypi/pico-feedback#417]
The [Getting started wiht Raspberry Pi Pico-series](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) contains inconsistencies regarding the default `PICO_BOARD=` build provided by the C/C++ SDK.

*On Page 35 (Red IMPORTANT Box)*

> The SDK builds binaries for the Raspberry Pi **Pico 2** by default

*On Page 39 (Red IMPORTANT Box)*

> The SDK builds binaries for the Raspberry Pi **Pico** by default

Both cannot be correct and it is confusing concerning whether a define is needed if building for `pico` or `pico2`?

Did the default build change from `pico` to `pico2`?

**Comment by lurch** [comment]
Default board (if neither `PICO_BOARD` nor `PICO_PLATFORM` are specified) is still `pico` - see https://github.com/raspberrypi/pico-sdk/blob/master/cmake/pico_pre_load_platform.cmake for the gory details :wink: 

The boxout on page 35 of the getting-started guide must have a typo.

**Comment by drankinatty** [comment]
Okay, good to know. Do you want me to pull a pull-request, or can somebody just delete the errant `'2'` without that formality?

**Comment by lurch** [comment]
You can't submit a pull-request, as the source-code for those PDFs isn't publicly available. But I'll ensure that this typo gets fixed internally, and updated PDFs get published within the next month or two. Thanks for spotting it!
