### ISSUE TITLE
pico-setup-windows issues are gone

### ISSUE THREAD

**Issue by Slion** [raspberrypi/pico-feedback#419]
Could we somehow get the issues from the now archived [pico-setup-windows](https://github.com/raspberrypi/pico-setup-windows) repository back?

Right now they are gone and as a result I have a few broken links.
That's not cool cause we spend time contributing stuff and suddenly it's not accessibly anymore.

This issue is definitely off topic in this repository but I did not know where to ask.

**Comment by lurch** [comment]
I've just prodded a colleague, and this should be fixed now?

**Comment by Slion** [comment]
Issues are back, thank you 🙏
