### ISSUE TITLE
RP2350 manual DMA minor suggestion

### ISSUE THREAD

**Issue by Beaumotplage** [raspberrypi/pico-feedback#421]
For the DMA, I think it might be worth mentioning in the Changes from RP2040 that the Ctrl/Trig register has been re-ordered.
I was wondering why my DMA transfers were running into each other and it's because the BUSY bit had moved.

I totally understand if the policy is that if users bypass the SDK drivers to poke hex into registers, then they should check every register when upgrading. It was a lazy mistake on my part that I'd bashed hex into a register instead of using a #define, but it had me scratching my head for a bit.

**Comment by Wren6991** [comment]
Sure, I've added a callout mentioning that the CTRL register layout has changed.

We try not to move fields, but we'll do it if it's necessary to preserve some other property we think is important (here it was the grouping of the second bit of `READ_INCR`/`WRITE_INCR` with the existing first bit). The `CTRL` register is likely to change again in future if `TREQ_SEL` needs to grow beyond 6 bits.
