### ISSUE TITLE
Flashing Pico via Rasperry Pi

### ISSUE THREAD

**Issue by hasenradball** [raspberrypi/pico-feedback#435]
Dear Docu Team,

why did you remove the docu part how to flash and debug the pico directly via pi?
It is so great doing so!!!

**Comment by lurch** [comment]
I think the main reason is because since that initial documentation was written, we've now created and released the [Debug Probe](https://www.raspberrypi.com/products/debug-probe/) which makes things **much** easier. Only one set of common instructions between Raspberry Pi OS, non-Pi Linux platforms, Windows and macOS.

**Comment by hasenradball** [comment]
Would suggest to keep this though in the appendix for completeness.
Where can I take a copy of the old version of documentation?

**Comment by hasenradball** [comment]
One other point to this topic.

It would be perfect for the docu if there would be an example task in VScode for:
a) flashing the pico
b) starting the debuging


Is there an hint for the old docu version?

**Comment by lurch** [comment]
> It would be perfect for the docu if there would be an example task in VScode for: a) flashing the pico b) starting the debuging

Did you forget to read Chapter 4 of https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf ?
ping @will-v-pi in case I've misunderstood the request.

> Is there an hint for the old docu version?

We don't provide old versions of the documentation, and we only provide support for what's written in the latest version of the documentation (which can always be found at https://datasheets.raspberrypi.com/ ).

**Comment by hasenradball** [comment]
@lurch  @will-v-pi 
What I mean here maybee wrongly explained…

with the extension in vsCode, will it also possible to flash and debug  the pico via raspberry pi directly?
I set up openocd to flash an debug the pico via 40 pin header of pi.

Will this already be possible?

**Comment by lurch** [comment]
> with the extension in vsCode, will it also possible to flash and debug the pico via raspberry pi directly?

As I've already tried to suggest, this is no longer directly supported; we only support using Debug Probe.
If you're able to get it working, then great we aren't going to stop you, but I'm afraid we won't be providing help with this.

Closing the issue.

**Comment by hasenradball** [comment]
understood.
