### ISSUE TITLE
Getting Started section 6.3.  Location of launch-raspberrypi-swd.json

### ISSUE THREAD

**Issue by rowpie** [raspberrypi/pico-feedback#46]
I feel that **section 6.3** of the **Getting Started** document needs to state that the file `launch-raspberrypi-swd.json` is in the directory: `ide/vscode`.   

The example code snippet after the first paragraph does provide this information but I feel it should be in the paragraph above too.

**Comment by lurch** [comment]
I've just had a look, and I think this is okay as-is. The full path is mentioned both in the code-block and also above the next block which shows the entire file-contents.
![image](https://user-images.githubusercontent.com/476186/108232229-7599fd00-713a-11eb-9bb4-691267c8508c.png)
