### ISSUE TITLE
Minor typo in Pico C/C++ SDK document section 2.5.2: "an a C"

### ISSUE THREAD

**Issue by rowpie** [raspberrypi/pico-feedback#47]
I think this is a typo?

Section 2.5.2.
Second paragraph of list item 2.

Change "an a" to "a" ?

> As of right now the exceptional event is an a C assert so these...
> As of right now the exceptional event is a C assert so these...

**Comment by lurch** [comment]
I've just checked, and this is already fixed in our internal version, so will be appearing publicly when we next publish the PDFs.
