### ISSUE TITLE
Installing picotool on Mac - symlink creation missing step

### ISSUE THREAD

**Issue by te-sveji-freddo** [raspberrypi/pico-feedback#48]
Hi, I was installing picotool (Appendix B) following the guide "getting started with pico" and I found that on macOS you need to add the picotool binary symlink to the /usr/local/bin folder in order to use as a command, otherwise macOS will  give the error "command not found".

The command is:
`sudo ln -s /Users/your-nickname/picotool/build/picotool /usr/local/bin`

Regards,
FT

**Comment by kilograham** [comment]
there is an issue for this in picotool repo already

**Comment by te-sveji-freddo** [comment]
> there is an issue for this in picotool repo already

Sorry, I can't find it

**Comment by aallan** [comment]
It's at raspberrypi/picotool#4.

**Comment by te-sveji-freddo** [comment]
> It's at [raspberrypi/picotool#4](https://github.com/raspberrypi/picotool/issues/4).

Thank you!
