### ISSUE TITLE
Please hurry and add FreeRTOS

### ISSUE THREAD

**Issue by versamodule** [raspberrypi/pico-feedback#5]
Its great to have dual cores, but without an RTOS, you are keeping our hands tied.

**Comment by JamesH65** [comment]
No we are not. We have provided plenty of functionality to access both cores. Spinlocks, mailboxes, mutexes etc.

**Comment by versamodule** [comment]
Ok, Ok... take your pills. No need to get your panties in a bunch. You seriously need to learn how to address people.

**Comment by aallan** [comment]
There will be an RTOS port at some point in the future.
