### ISSUE TITLE
Getting started - chapter 8: PWM LED

### ISSUE THREAD

**Issue by MatejPavel** [raspberrypi/pico-feedback#51]
When explaining PWM in the book (page 102), the first exmaple uses machine.PWM.duty() to set a 10-bit value as the LED duty cycle. 

machine.PWM does not have "duty" as an attribute in the latest provided micropyton binary (2021/01/21). The book should probably be updated to go straight to duty_u16().

**Comment by benevpi** [comment]
Whoops. That looks like it slipped in from an earlier version. We're just checking through an updated version of the book now, and this is fixed in that.
