### ISSUE TITLE
Raspberry Pi Pico C/C++ SDK, 2.3.3. Hardware Support Libraries

### ISSUE THREAD

**Issue by fivdi** [raspberrypi/pico-feedback#53]
In release 1.2 of the Raspberry Pi Pico C/C++ SDK documentation, in section 2.3.3. Hardware Support Libraries, at the top of page 14, in the red note box, the following text appears:

```
In such cases, the compiler is often able to fold the code down to to a single register write
```

It should be:
```
In such cases, the compiler is often able to fold the code down to a single register write
```

**Comment by lurch** [comment]
Thanks. Fixed internally - expect to see it in V1.3 of the PDFs (which have no ETA yet).
