### ISSUE TITLE
Datasheet has some headers as last item on a page

### ISSUE THREAD

**Issue by Muximize** [raspberrypi/pico-feedback#55]
This can be confusing. Is the toolchain generating the docs smart or configurable enough to fix this without using page breaks?

**Example 1:**
>![image](https://user-images.githubusercontent.com/2208470/106525197-e9ee6280-64e3-11eb-9866-c20c234ee906.png)

**Example 2:**
>![image](https://user-images.githubusercontent.com/2208470/106524927-82d0ae00-64e3-11eb-8fc8-a1023cb0f758.png)

**Example 3:**
>![image](https://user-images.githubusercontent.com/2208470/106525667-9fb9b100-64e4-11eb-8b2d-e3c58d446672.png)

**Comment by aallan** [comment]
There is some flexibility, and some smarts already built into the toolchain. But in the end it is taking a whole bunch of asciidoc text, TSV files generated directly from the RTL for the register tables, XML generated from Doxygen documentation, and a few other things, and squishing it all together. There are going to be corner cases.

I'll add this to the internal list of "irritating things the toolchain does that we want to fix at some point". Thanks.
