### ISSUE TITLE
C SDK output to USB drops last character(s) in minicom

### ISSUE THREAD

**Issue by Hermann-SW** [raspberrypi/pico-feedback#57]
This is output in minicom, after disconnecting and connecting minicom several times.
The connected message should appear in next row, not directly after "done":
```
Port /dev/ttyACM0, 05:39:13

Press CTRL-A Z for help on special keys               
                                                      
tud_cdc_connected()                                   
donetud_cdc_connected()                               
donetud_cdc_connected()                               
done
```

Code:
```
#include <stdlib.h>
#include "pico/stdlib.h"
#include <tusb.h>

int main(void) {
  stdio_init_all();
  while (!tud_cdc_connected()) { sleep_ms(100);  }
  printf("tud_cdc_connected()\n");
  printf("done\n"); fflush(stdout);

  return 0;
}
```

**Comment by Hermann-SW** [comment]
This is a bug report, not a question

**Comment by lurch** [comment]
@aallan Should this be re-opened and moved to pico-sdk ?

**Comment by aallan** [comment]
> Should this be re-opened and moved to pico-sdk ?

I've seen no further reports of this happening, so I'm presuming it's user-specific issue rather than a general problem

**Comment by lurch** [comment]
@Hermann-SW Was this just a "glitch", or is it still reproducible with the latest `develop` version of Raspberry Pi Pico SDK?

**Comment by Hermann-SW** [comment]
What and how do I need to update in order to answer the question?

**Comment by lurch** [comment]
You need to update your `pico-sdk` directory to use the `develop` branch: https://github.com/raspberrypi/pico-sdk/tree/develop

If you've already got a `pico-sdk` directory, you should be able to `git checkout develop; git pull`
