### ISSUE TITLE
Install Pico SDK by default on Raspberry Pi OS

### ISSUE THREAD

**Issue by pxeger** [raspberrypi/pico-feedback#6]
It would be great if the Pico SDK could be pre-installed and pre-compiled on Raspberry Pi OS + desktop and recommended software images to avoid having to spend an hour watching it compile and install all the dependencies in front of me.

**Comment by aallan** [comment]
There is a link to the source code in Git above every example in the book. Just click on the link to go directly to the raw source code.

**Comment by pxeger** [comment]
What does that have to with my question? Did you comment on the wrong issue?

**Comment by JamesH65** [comment]
This was considered, and may still happen, but we are trying to keep the base Raspberry Pi OS image size down.

**Comment by daveythacher** [comment]
It may be possible to add a module into the apt-get system. You can do this without them.

I get the point they are making however it could be a fat image or configurable image installer. I think they have some logic for this released.
