### ISSUE TITLE
RP2040 PI PICO - DMA

### ISSUE THREAD

**Issue by irishconger** [raspberrypi/pico-feedback#61]
Cant really see how this works for RP2040 PI PICO.

From other controllers, you would have:
SOURCE BUFFER LOCATION -- with or without auto-increment
DESTINATION BUFFER LOCATION -- with or without auto-increment
NUMBER OF TRANSFERS (e.g. transfer 1k values)
TRIGGER EVENT for DMA transfer (e.g. ADConversion is done)
REPORT EVENT ON NUMBER OF TRANSFERS COMPLETE (e.g. generate interrupt)
AUTO-TRIGGER ON NUMBER OF TRANSFERS COMPLETE (e.g. swap to alternate buffer -  this would allow for seamless 'continuous' transfer of ADC samples)

How do these map to RP2040 PI PICO?

g

**Comment by lurch** [comment]
Are there _specific_ questions you have that section "2.5. DMA" of https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf doesn't answer? Have a look also at https://github.com/raspberrypi/pico-examples/tree/master/dma

**Comment by irishconger** [comment]
Thanks Andy.... I was using out of date documentation.
Indeed, most of the functionality I was looking for is covered in the doc u
referenced.
g
