### ISSUE TITLE
https://rptl.io/pico-get-started  doesn't work and other Readme.md quibbles.

### ISSUE THREAD

**Issue by albertvanderhorst** [raspberrypi/pico-feedback#62]
If I try to open 
https://rptl.io/pico-get-started  I got redirected to the general Raspbery website.
The same for the other references starting with rptl.io.
I have no clue how to get information how to use this development system. 

This should be replaced by a reference to the general Raspberry website, and then an advise how to navigate. I have made comments like this before, and the answer was: "find things out and push a better Readme.md" . Finding things out will take me hours if not days, and you guys know it by heart.

**Comment by JamesH65** [comment]
Works correctly for me as well. What browser are you using?
