### ISSUE TITLE
Inconsistent use of pullup and pull-up

### ISSUE THREAD

**Issue by PeterOGB** [raspberrypi/pico-feedback#70]
In the RP2040 data sheet the hyphenated and non-hyphenated versions of "pullup/pull-up" are used.
The same applies for "pulldown/pull-down"

This means you have to search the document twice to find all the information !

**Comment by aallan** [comment]
@lurch Did you get round to do a find-and-replace for this one?

**Comment by lurch** [comment]
Not yet, it never floated to the top of my priority list!

**Comment by JamesH65** [comment]
Just reported on the forums as well. https://www.raspberrypi.org/forums/viewtopic.php?f=144&t=315020

**Comment by PeterOGB** [comment]
How is telling the poster on the forums it's been reported, but not telling them nothing has been done about it in five months helpful ?
Clearly no one thinks it's important so I'll just close it as "Wont Fix"

**Comment by aallan** [comment]
It's on the list.

**Comment by PeterOGB** [comment]
You are taking the piss !

**Comment by dp111** [comment]
There is a third variant as well "pull up" / "pull down"

**Comment by issa-tseng** [comment]
i tried to give this a go but either i'm stupid or the pdf documentations aren't public for contributions?

**Comment by aallan** [comment]
> i tried to give this a go but either i'm stupid or the pdf documentations aren't public for contributions?

The source of the PDF documentation is not public.

**Comment by issa-tseng** [comment]
okay, thanks for the clarification! was just hoping to give back a bit. :)

**Comment by aallan** [comment]
Fixed in the next docs release.
