### ISSUE TITLE
BUSCTRL_PERSELx registers should link back to the 2.1.1.2. Bus Performance Counters section

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/pico-feedback#71]
i was having trouble figuring out what enum the BUSCTRL_PERSELx registers used, since they dont link back to the enum, you have to instead just blindly ctrl+f for the register name or stumble upon it while trying to find the PERSEL register

**Comment by Wren6991** [comment]
The values are now enumerated in the register table in the upstream datasheet. There's a PR to add these values to the headers and SVD too.
