### ISSUE TITLE
Wrong heading in ”Getting started with Raspberry Pi Pico”

### ISSUE THREAD

**Issue by kennethjohnsen** [raspberrypi/pico-feedback#74]
I have found a minor issue in ”Getting started with Raspberry Pi Pico” (https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf).
On page 36, the heading says ”Installing Visual Studio Code”, but the instructions are actually for installing the build tools for VS2019.

**Comment by aallan** [comment]
Yup. Many thanks. This one has already been fixed upstream and will appear in the next PDF docs release.
