### ISSUE TITLE
Add pointers to practical flash programming info.

### ISSUE THREAD

**Issue by PiGraham** [raspberrypi/pico-feedback#78]
It would be useful to reference in the contents that SWD is a convenient way to flash code to the PICO, avoiding the need to reboot with BOOTSEL pressed. It might also be a good idea to make that info a bit more prominent. It seems to be just this on Pg. 20:

> and load hello_world.elf into flash,
The following code illustrating commands to do that.

Maybe a heading "Easy Flash programming with SWD" or something like that.
And maybe a line to the effect: "it is not necessary to use the BOOTSEL button to program code into the flash if you connect an SWD interface."

**Comment by Wren6991** [comment]
Thanks for raising this, it's important and this is a common theme we have seen. I added this section at the end of chapter 3:
![image](https://user-images.githubusercontent.com/1298595/107518990-92b55580-6ba7-11eb-91ee-b5016b4becd6.png)

Title of chapter 5 is changed from "Debugging with SWD" to "Flash Programming and Debug with SWD":
![image](https://user-images.githubusercontent.com/1298595/107519039-a52f8f00-6ba7-11eb-8833-ef040afe7c95.png)

This new paragraph is at the top of chapter 5:

![image](https://user-images.githubusercontent.com/1298595/107519079-b2e51480-6ba7-11eb-8841-60c23c7e4018.png)

**Comment by Wren6991** [comment]
We're also looking at ways of making the USB bootloader flow nicer (some way of resetting the board over USB if USB-serial is present in the binary) but this needs some more work and lots of testing across platforms.
