### ISSUE TITLE
Debugging Pico with ST-Link

### ISSUE THREAD

**Issue by KamamiBTC** [raspberrypi/pico-feedback#79]
Hi, 

Is there a possibility to debug code on Pico with ST-LINK/V2 probe? If yes, is there any instruction how to connect it via VS Code on MS Windows?

**Comment by aallan** [comment]
RP2040 uses multi-drop SWD so the ST-Link needs to support that. The major problem is that despite backwards compatibility in the protocols, at startup no device is selected on the bus, therefore you have to select one of the cores before you talk to it (also if you want to debug both cores, ST-Link has to support that as well). 

We have no experience with the ST-Link and RP2040 (or Pico). Probably the best place to start investigating whether support was possible would be the [ST Community](https://community.st.com/s/).
