### ISSUE TITLE
Erroneous command in getting started guide

### ISSUE THREAD

**Issue by ConfuSomu** [raspberrypi/pico-feedback#8]
In the _Getting started with Raspberry Pi Pico_ guide, section 6.3 "Debugging a project" at page 23, it is stated that one should copy `ide/vscode/launch-raspberrypi-swd.json` to `.vscode/settings.json`. Instead, `ide/vscode/settings.json` should be copied to `.vscode/settings.json`. Accordingly, the last line on the terminal prompt should be replaced with:

```bash
$ cp ide/vscode/settings.json .vscode/settings.json
```

Apart this minor nitpick, great job on the documentation!

**Comment by lurch** [comment]
Fixed internally, will make its way to the next version of the PDFs.
