### ISSUE TITLE
drive strength

### ISSUE THREAD

**Issue by benevpi** [raspberrypi/pico-feedback#87]
What's the drive strength used in MicroPython?

The following isn't telling me, but I've not used this before, so I'm not sure if this isn't implemented in this port or I'm doing it wrong.

```
>>> import machine
>>> pin = machine.Pin(25)
>>> pin.drive()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Pin' object has no attribute 'drive'
>>> 
```

**Comment by aallan** [comment]
@benevpi Now it's upstreamed might be best to open an issue on the main micropython repo?
