### ISSUE TITLE
RP2040: USB Device Controller: Feature Request - Stop on Short Packet

### ISSUE THREAD

**Issue by swetland** [raspberrypi/pico-feedback#97]
Some USB protocols over BULK endpoints use a short packet to indicate end-of-transaction.

Unfortunately, when using double-buffering on BULK OUT endpoints, one can end up with one buffer still ready-to-receive (Available bit set in Buffer Control Register) when a short packet arrives on the other other buffer.  It is unclear if it is safe to "disarm" the remaining buffer (and how quickly one must do so to avoid accidentally receiving the first packet of the next transaction).

Ideally a STOP_ON_SHORT_PACKET bit in the Endpoint Control Register, when set, would cause that endpoint to NAK further transfers until the condition was cleared.  This could be accomplished by having both Available bits in the corresponding Buffer Control Register clear when the condition occurs, or assuming the Abort errata is fixed, by automatically asserting the corresponding bit in the Abort register.

**Comment by aallan** [comment]
Hey, it's been added to the internal list.
